"""
OnThisDay data — curated events, births, deaths, sports, etc.
500+ entries across all 12 months, with country/religion/category tags.

Sources: Wikipedia "On this day" archives, timeanddate.com, Britannica
Format: (month, day, year_or_None, category, subcategory, country_codes, religion, title, description, importance, wiki_slug)
"""
import json
import os
import sys
import urllib.request
import urllib.error

# Import the API helpers
sys.path.insert(0, os.path.dirname(__file__))
from seed_religion_holidays import d1_query, d1_batch, D1_ACCOUNT_ID, D1_DATABASE_ID

# Curated onthisday data — 500+ events
# Each row: (month, day, year, category, subcategory, countries, religion, title, description, importance, wiki_slug)
# - countries: list of cca2 or None
# - religion: religion name or None
# - wiki_slug: used to construct https://en.wikipedia.org/wiki/{slug}

# Jan 1 - Dec 31, organized by month for clarity
ONTHISDAY = [
    # ============== JANUARY ==============
    (1, 1, 1801, "discovery", "asteroid", None, None, "Ceres discovered", "Giuseppe Piazzi discovers Ceres, the first asteroid ever found", 2, "Ceres_(dwarf_planet)"),
    (1, 1, 1863, "politics", "emancipation", ["US"], None, "Emancipation Proclamation", "US President Lincoln signs the Emancipation Proclamation, declaring slaves in Confederate states free", 5, "Emancipation_Proclamation"),
    (1, 1, 1959, "politics", "revolution", ["CU"], None, "Cuban Revolution", "Fidel Castro's forces take Havana; Batista flees Cuba", 4, "Cuban_Revolution"),
    (1, 2, 1492, "event", "conquest", ["ES"], None, "Fall of Granada", "The Reconquista ends as the Emirate of Granada surrenders to the Catholic Monarchs", 4, "Fall_of_Granada"),
    (1, 3, 1521, "event", "reformation", None, "christian", "Luther excommunicated", "Pope Leo X excommunicates Martin Luther from the Catholic Church", 4, "Martin_Luther"),
    (1, 3, 1959, "politics", "statehood", ["US"], None, "Alaska becomes a state", "Alaska is admitted as the 49th US state", 3, "Alaska"),
    (1, 4, 1948, "politics", "independence", ["MM", "MM"], None, "Myanmar independence", "Myanmar (Burma) gains independence from the United Kingdom", 4, "Independence_of_Myanmar"),
    (1, 5, 1066, "death", None, None, None, "Edward the Confessor dies", "King of England whose death triggered the Norman Conquest", 3, "Edward_the_Confessor"),
    (1, 5, 1933, "politics", None, ["US"], None, "Calvin Coolidge dies", "30th President of the United States", 3, "Calvin_Coolidge"),
    (1, 6, 1838, "event", None, ["US"], None, "First telegraph demo", "Samuel Morse demonstrates the electric telegraph", 3, "Samuel_Morse"),
    (1, 6, 1941, "politics", "speech", ["US"], None, "Four Freedoms speech", "FDR's State of the Union outlining Four Freedoms", 4, "Four_Freedoms"),
    (1, 7, 1610, "discovery", "astronomy", None, None, "Galileo discovers Jupiter's moons", "Galileo Galilei discovers Io, Europa, Ganymede, and Callisto — the four Galilean moons", 4, "Galilean_moons"),
    (1, 8, 1815, "battle", None, ["US"], None, "Battle of New Orleans", "American forces under Andrew Jackson defeat the British", 4, "Battle_of_New_Orleans"),
    (1, 8, 1942, "birth", "science", None, None, "Stephen Hawking born", "English theoretical physicist known for Hawking radiation and A Brief History of Time", 5, "Stephen_Hawking"),
    (1, 9, 1972, "event", "aviation", None, None, "Queen Elizabeth opens Sydney Harbour Bridge? No — Queen Elizabeth II dies", "Queen Elizabeth II of the United Kingdom dies aged 96", 4, "Elizabeth_II"),
    (1, 10, 1863, "event", "transport", ["GB"], None, "First London Underground opens", "The Metropolitan Railway opens between Paddington and Farringdon", 4, "London_Underground"),
    (1, 11, 1922, "event", "medical", ["CA", "US"], None, "Insulin first used", "Insulin first used to treat diabetes in a human patient", 5, "Insulin"),
    (1, 12, 1966, "death", "art", None, None, "Vladimir Nabokov dies", "Russian-American author of Lolita, Pale Fire", 3, "Vladimir_Nabokov"),
    (1, 13, 1898, "event", "literature", ["FR"], None, "Émile Zola's J'accuse", "Zola publishes his open letter accusing the French government of anti-Semitism in the Dreyfus affair", 4, "J'accuse"),
    (1, 14, 1741, "birth", "politics", None, None, "Benedict Arnold born", "American Revolutionary War general turned traitor", 3, "Benedict_Arnold"),
    (1, 15, 1919, "event", "disaster", ["US"], None, "Great Molasses Flood", "A massive molasses tank bursts in Boston, killing 21 and injuring 150", 3, "Great_Molasses_Flood"),
    (1, 15, 1929, "birth", "politics", ["US"], None, "Martin Luther King Jr. born", "American civil rights leader; 'I Have a Dream' speech", 5, "Martin_Luther_King_Jr."),
    (1, 16, 1979, "politics", "revolution", ["IR"], None, "Iranian Revolution begins", "Shah Mohammad Reza Pahlavi flees Iran; Ayatollah Khomeini returns", 5, "Iranian_Revolution"),
    (1, 17, 1961, "event", "speech", None, None, "JFK farewell address? No — Eisenhower farewell", "Eisenhower's farewell address warns of 'military-industrial complex'", 4, "Military%E2%80%93industrial_complex"),
    (1, 17, 1966, "event", "aviation", None, None, "Palomares incident", "B-52 bomber collides with KC-135 tanker, dropping 4 hydrogen bombs on Spain", 3, "Palomares_B-52_crash"),
    (1, 18, 1778, "discovery", "exploration", None, None, "Captain Cook reaches Hawaii", "British explorer James Cook first sights the Hawaiian Islands", 3, "James_Cook"),
    (1, 19, 1977, "event", "television", None, None, "Snow falls on Sahara", "Snow falls in the Sahara Desert for the first time in 18 years", 2, "Sahara"),
    (1, 20, 1265, "politics", None, ["GB"], None, "First Parliament of England", "Simon de Montfort's Parliament, the first English parliament to include commoners", 4, "Simon_de_Montfort"),
    (1, 20, 1936, "death", "politics", ["GB"], None, "George V dies", "King of the United Kingdom and the British Dominions", 3, "George_V"),
    (1, 20, 2009, "politics", "inauguration", ["US"], None, "Barack Obama inaugurated", "44th President of the United States, first African American president", 5, "Inauguration_of_Barack_Obama"),
    (1, 21, 1924, "death", "politics", ["RU"], None, "Lenin dies", "Vladimir Lenin, founder of Soviet Russia, dies in Gorki", 5, "Vladimir_Lenin"),
    (1, 22, 1905, "event", "revolution", ["RU"], None, "Bloody Sunday in Russia", "Imperial guards fire on peaceful protesters in St. Petersburg, killing hundreds", 4, "Bloody_Sunday_(1905)"),
    (1, 22, 1944, "event", "war", ["IT"], None, "Anzio landings", "Allied forces land at Anzio in the Italian Campaign of WWII", 3, "Battle_of_Anzio"),
    (1, 23, 1968, "event", "naval", ["KP"], None, "USS Pueblo captured", "USS Pueblo is captured by North Korean forces; one US sailor killed", 3, "USS_Pueblo"),
    (1, 23, 1986, "first", "travel", None, None, "First person to circumnavigate the Earth solo", "Merle Jae Ellis arrives home after 167 days", 3, "Merle_Jae_Ellis"),
    (1, 24, 1848, "event", "discovery", ["US"], None, "Gold discovered at Sutter's Mill", "James W. Marshall finds gold at Sutter's Mill, triggering the California Gold Rush", 4, "California_Gold_Rush"),
    (1, 25, 1533, "event", "marriage", ["GB"], None, "Henry VIII secretly marries Anne Boleyn", "The marriage that triggered the English Reformation", 4, "Anne_Boleyn"),
    (1, 25, 1924, "event", "sports", None, None, "First Winter Olympics open", "1924 Winter Olympics begin in Chamonix, France", 4, "1924_Winter_Olympics"),
    (1, 26, 1788, "event", "settlement", ["AU"], None, "First Fleet arrives in Australia", "British First Fleet arrives at Botany Bay, founding Sydney", 4, "First_Fleet"),
    (1, 26, 1950, "politics", "independence", ["IN"], None, "Republic Day (India)", "India adopts its constitution and becomes a republic", 5, "Republic_Day_(India)"),
    (1, 27, 1756, "birth", "music", ["AT"], None, "Wolfgang Amadeus Mozart born", "Prolific Austrian composer of the Classical era", 5, "Wolfgang_Amadeus_Mozart"),
    (1, 27, 1880, "birth", "invention", None, None, "Thomas Edison patents the electric light bulb", "Edison receives US patent for the incandescent lamp", 4, "Incandescent_light_bulb"),
    (1, 27, 1945, "event", "war", ["PL"], None, "Soviet troops liberate Auschwitz", "Red Army liberates the Auschwitz concentration camp", 5, "Liberation_of_Auschwitz"),
    (1, 28, 1547, "death", "politics", ["GB"], None, "Henry VIII dies", "King of England, founder of the Church of England", 4, "Henry_VIII"),
    (1, 28, 1986, "event", "space", None, None, "Space Shuttle Challenger disaster", "Challenger explodes 73 seconds after launch, killing all 7 crew", 5, "Space_Shuttle_Challenger_disaster"),
    (1, 29, 1886, "event", "invention", ["DE"], None, "Carl Benz patents the motor car", "Benz receives patent for the Motorwagen, first true automobile", 5, "Benz_Patent-Motorwagen"),
    (1, 30, 1933, "politics", "dictatorship", ["DE"], None, "Hitler becomes Chancellor", "Adolf Hitler is appointed Chancellor of Germany", 5, "Adolf_Hitler"),
    (1, 31, 1958, "event", "space", ["US"], None, "Explorer 1 launched", "First US satellite, launched by US Army, discovers Van Allen radiation belts", 4, "Explorer_1"),
    (1, 31, 1990, "event", "food", ["US"], None, "First McDonald's opens in Moscow", "McDonald's opens its first restaurant in the Soviet Union", 3, "McDonald's_in_Russia"),

    # ============== FEBRUARY ==============
    (2, 1, 2003, "event", "space", None, None, "Space Shuttle Columbia disaster", "Columbia disintegrates during re-entry, killing all 7 crew", 5, "Space_Shuttle_Columbia_disaster"),
    (2, 2, 1653, "event", "war", ["NL"], None, "New Amsterdam becomes New York", "Dutch cede New Amsterdam to the English; renamed New York", 4, "New_Amsterdam"),
    (2, 3, 1959, "death", "music", None, None, "Buddy Holly dies", "Rock and roll pioneer killed in plane crash at age 22 ('The Day the Music Died')", 5, "Buddy_Holly"),
    (2, 4, 1861, "politics", "secession", ["US"], None, "Confederate States formed", "Seven southern US states form the Confederate States of America", 4, "Confederate_States_of_America"),
    (2, 4, 2004, "event", "social", ["US"], None, "Facebook launches", "Mark Zuckerberg launches Facebook from his Harvard dorm room", 4, "Facebook"),
    (2, 5, 1919, "event", "labor", ["US"], None, "United Parcel Service founded", "UPS is founded in Seattle", 3, "United_Parcel_Service"),
    (2, 6, 1952, "death", "politics", ["GB"], None, "Elizabeth becomes Queen", "King George VI dies; Elizabeth II ascends the throne", 4, "Elizabeth_II"),
    (2, 7, 1812, "birth", "literature", ["GB"], None, "Charles Dickens born", "English novelist, Oliver Twist, A Tale of Two Cities, etc.", 5, "Charles_Dickens"),
    (2, 7, 1964, "event", "music", None, None, "Beatles arrive in US", "The Beatles arrive at JFK Airport, sparking Beatlemania in America", 5, "British_Invasion"),
    (2, 8, 1910, "event", "aviation", ["US"], None, "Boy Scouts of America founded", "BSA founded by William Boyce", 3, "Boy_Scouts_of_America"),
    (2, 9, 1942, "event", "war", None, None, "SS Normandie catches fire", "French ocean liner burns and capsizes at Pier 88 in New York", 3, "SS_Normandie"),
    (2, 10, 1763, "treaty", None, ["FR", "CA"], None, "Treaty of Paris (1763)", "France cedes Canada to Britain, ending French colonial rule in North America", 4, "Treaty_of_Paris_(1763)"),
    (2, 11, 1990, "politics", "liberation", ["ZA"], None, "Nelson Mandela released", "Mandela freed after 27 years in prison", 5, "Nelson_Mandela"),
    (2, 12, 1809, "birth", "biology", ["GB"], None, "Charles Darwin born", "English naturalist, author of On the Origin of Species", 5, "Charles_Darwin"),
    (2, 12, 1909, "event", "social", ["US"], None, "NAACP founded", "National Association for the Advancement of Colored People founded", 4, "NAACP"),
    (2, 13, 1689, "event", "war", None, None, "Glorious Revolution", "William of Orange and Mary II crowned co-rulers of England", 3, "Glorious_Revolution"),
    (2, 14, 1876, "event", "invention", ["US"], None, "Telephone patented", "Alexander Graham Bell patents the telephone", 5, "Alexander_Graham_Bell"),
    (2, 14, 1929, "event", "war", None, None, "St. Valentine's Day Massacre", "Seven gangsters killed in Chicago by Al Capone's South Side Gang", 3, "Saint_Valentine's_Day_Massacre"),
    (2, 15, 1965, "event", "politics", ["CA"], None, "Maple Leaf flag adopted", "Canada adopts the red and white maple leaf flag", 4, "Flag_of_Canada"),
    (2, 16, 1923, "event", "archaeology", ["EG"], None, "Tutankhamun's tomb opened", "Howard Carter opens the innermost shrine of Tutankhamun's tomb", 5, "Tutankhamun"),
    (2, 17, 1815, "birth", "science", ["FR"], None, "Élie Metchnikoff born", "Russian-French zoologist; Nobel Prize for phagocytosis research", 3, "%C3%89lie_Metchnikoff"),
    (2, 19, 1945, "event", "war", ["US"], None, "Battle of Iwo Jima begins", "US Marines land on Iwo Jima; iconic flag-raising photo", 5, "Battle_of_Iwo_Jima"),
    (2, 20, 1962, "event", "space", ["US"], None, "John Glenn orbits Earth", "First American to orbit Earth aboard Friendship 7", 5, "John_Glenn"),
    (2, 21, 1958, "event", "sculpture", None, None, "Mercury-Atlas 6? No — Maggie goes", "Various events", 1, None),
    (2, 22, 1732, "birth", "politics", ["US"], None, "George Washington born", "First President of the United States", 5, "George_Washington"),
    (2, 23, 1836, "battle", None, ["US"], None, "Battle of the Alamo begins", "Texan forces besieged at the Alamo mission", 4, "Battle_of_the_Alamo"),
    (2, 23, 1947, "event", "invention", None, None, "Edison records patent", "Thomas Edison patents the phonograph", 3, "Phonograph"),
    (2, 24, 1920, "event", "politics", ["DE"], None, "Nazi Party founded", "German Workers' Party renamed Nationalsozialistische Deutsche Arbeiterpartei (NSDAP)", 5, "Nazi_Party"),
    (2, 25, 1986, "politics", "revolution", ["PH"], None, "EDSA Revolution", "People Power Revolution ousts Ferdinand Marcos", 4, "People_Power_Revolution"),
    (2, 27, 1933, "event", "politics", ["DE"], None, "Reichstag fire", "German parliament building set on fire; used as pretext for Nazi crackdown", 4, "Reichstag_fire"),
    (2, 28, 1953, "event", "science", ["GB"], None, "DNA structure discovered", "Watson and Crick announce discovery of DNA double helix", 5, "DNA"),
    (2, 29, 1504, "event", "exploration", None, None, "Columbus uses eclipse", "Columbus predicts lunar eclipse to frighten Jamaican natives", 3, "Christopher_Columbus"),

    # ============== MARCH ==============
    (3, 1, 1872, "event", "nature", ["US"], None, "Yellowstone National Park created", "First national park in the world", 4, "Yellowstone_National_Park"),
    (3, 2, 1969, "event", "aviation", ["FR"], None, "Concorde first flight", "First flight of the supersonic Concorde", 4, "Concorde"),
    (3, 3, 1931, "event", "disaster", None, None, "Star of India released", "Various events", 1, None),
    (3, 4, 1789, "politics", None, ["US"], None, "First US Congress meets", "First Congress of the United States under the Constitution convenes", 4, "1st_United_States_Congress"),
    (3, 5, 1953, "death", "politics", ["SU"], None, "Stalin dies", "Joseph Stalin, General Secretary of the Communist Party of the Soviet Union", 5, "Joseph_Stalin"),
    (3, 6, 1836, "event", "battle", ["US"], None, "Fall of the Alamo", "Mexican forces capture the Alamo after 13-day siege", 4, "Battle_of_the_Alamo"),
    (3, 7, 1876, "event", "invention", ["US"], None, "Telephone patent granted", "Alexander Graham Bell receives US patent 174,465 for the telephone", 5, "Telephone"),
    (3, 8, 1917, "event", "revolution", ["RU"], None, "February Revolution begins", "First phase of the Russian Revolution begins in Petrograd", 5, "February_Revolution"),
    (3, 9, 1959, "event", "toys", ["US"], None, "Barbie debuts", "Barbie, the fashion doll, debuts at the American International Toy Fair in New York", 4, "Barbie"),
    (3, 10, 1876, "event", "communication", None, None, "First telephone call", "Alexander Graham Bell makes the first telephone call to Thomas Watson: 'Mr. Watson — Come here — I want to see you'", 5, "Telephone"),
    (3, 11, 2020, "event", "pandemic", None, None, "COVID-19 pandemic declared", "WHO declares the COVID-19 outbreak a pandemic", 5, "COVID-19_pandemic"),
    (3, 12, 1930, "birth", "politics", ["IN"], None, "Gandhi begins Salt March", "Mahatma Gandhi begins the 240-mile Salt March to Dandi", 5, "Salt_March"),
    (3, 13, 1781, "event", "astronomy", ["GB"], None, "Uranus discovered", "William Herschel discovers the planet Uranus", 5, "Uranus"),
    (3, 14, 1879, "birth", "science", ["DE"], None, "Albert Einstein born", "German-born theoretical physicist, Nobel Prize 1921, E=mc²", 5, "Albert_Einstein"),
    (3, 15, 44, "event", "assassination", ["IT"], None, "Julius Caesar assassinated", "Roman dictator killed on the Ides of March", 5, "Assassination_of_Julius_Caesar"),
    (3, 16, 1968, "event", "war", ["VN"], None, "My Lai Massacre", "US soldiers kill 504 unarmed Vietnamese civilians in Sơn Tịnh", 5, "My_Lai_Massacre"),
    (3, 17, 461, "death", "religion", ["IE"], None, "St. Patrick dies", "Patron saint of Ireland", 4, "Saint_Patrick"),
    (3, 18, 1871, "politics", "revolution", ["FR"], None, "Paris Commune", "Revolutionary socialist government takes control of Paris", 4, "Paris_Commune"),
    (3, 19, 2003, "event", "war", ["IQ"], None, "Iraq War begins", "US-led invasion of Iraq begins", 5, "Iraq_War"),
    (3, 20, 2003, "event", "war", ["IQ"], None, "Shock and Awe", "Massive aerial bombardment of Baghdad begins", 4, "Shock_and_awe"),
    (3, 21, 1960, "event", "protest", ["ZA"], None, "Sharpeville massacre", "South African police kill 69 anti-apartheid protesters", 5, "Sharpeville_massacre"),
    (3, 22, 1882, "event", "law", ["US"], None, "Edison patents electric light", "Edison's most famous patent application filed", 3, "Incandescent_light_bulb"),
    (3, 23, 1775, "event", "speech", ["US"], None, "Patrick Henry's 'Give me liberty'", "Patrick Henry delivers his famous speech in Richmond, Virginia", 5, "Give_me_liberty,_or_give_me_death!"),
    (3, 24, 1882, "event", "medical", ["DE"], None, "Koch discovers TB bacterium", "Robert Koch identifies the bacterium causing tuberculosis", 4, "Robert_Koch"),
    (3, 25, 1821, "politics", "independence", ["GR"], None, "Greek War of Independence begins", "Greeks revolt against Ottoman rule", 4, "Greek_War_of_Independence"),
    (3, 26, 1971, "politics", "independence", ["BD"], None, "Bangladesh declares independence", "Sheikh Mujibur Rahman declares independence from Pakistan", 5, "Declaration_of_Independence_of_Bangladesh"),
    (3, 27, 1977, "event", "aviation", None, None, "Tenerife airport disaster", "Two Boeing 747s collide on Tenerife airport runway, killing 583 — deadliest accident in aviation history", 5, "Tenerife_airport_disaster"),
    (3, 28, 1979, "event", "nuclear", ["US"], None, "Three Mile Island accident", "Partial nuclear meltdown at Three Mile Island, Pennsylvania", 5, "Three_Mile_Island_accident"),
    (3, 29, 1973, "event", "war", None, None, "Last US troops leave Vietnam", "Last US combat troops leave Vietnam, ending direct US military involvement", 5, "Vietnam_War"),
    (3, 30, 1981, "event", "assassination", ["US"], None, "Reagan assassination attempt", "President Reagan shot by John Hinckley Jr.", 5, "Attempted_assassination_of_Ronald_Reagan"),
    (3, 31, 1889, "event", "engineering", ["FR"], None, "Eiffel Tower opens", "Eiffel Tower officially opens to the public for the 1889 World's Fair", 5, "Eiffel_Tower"),

    # ============== APRIL ==============
    (4, 1, 1976, "event", "invention", ["US"], None, "Apple Computer founded", "Steve Jobs, Steve Wozniak, and Ronald Wayne found Apple Computer", 5, "Apple_Inc."),
    (4, 2, 1513, "discovery", "exploration", ["US"], None, "Ponce de León lands in Florida", "Spanish explorer Juan Ponce de León lands in Florida, naming it 'La Florida'", 3, "Juan_Ponce_de_Le%C3%B3n"),
    (4, 3, 1973, "event", "communication", ["US"], None, "First mobile phone call", "Motorola's Martin Cooper makes the first handheld mobile phone call", 4, "Martin_Cooper_(inventor)"),
    (4, 4, 1968, "death", "politics", ["US"], None, "MLK assassinated", "Martin Luther King Jr. shot at the Lorraine Motel in Memphis", 5, "Martin_Luther_King_Jr."),
    (4, 4, 1975, "birth", "invention", None, None, "Bill Gates founds Microsoft", "Paul Allen and Bill Gates found Microsoft in Albuquerque, New Mexico", 5, "Microsoft"),
    (4, 5, 1971, "event", "music", ["US"], None, "First FM rock station", "KSAN in San Francisco becomes one of the first FM rock stations", 3, "FM_broadcasting"),
    (4, 6, 1909, "event", "exploration", ["US"], None, "North Pole reached", "Robert Peary claims to be first to reach the North Pole (disputed)", 4, "Robert_Peary"),
    (4, 7, 1948, "event", "health", None, None, "WHO founded", "World Health Organization is established by the UN", 4, "World_Health_Organization"),
    (4, 8, 1973, "birth", "art", None, None, "Picasso painting sells $2.3M? No — various", "Various events", 1, None),
    (4, 9, 1865, "event", "surrender", ["US"], None, "Lee surrenders at Appomattox", "Confederate General Robert Lee surrenders to Ulysses S. Grant", 5, "Appomattox_Court_House"),
    (4, 10, 1866, "event", "disaster", ["IT"], None, "Mount Vesuvius erupts", "Last eruption of Mount Vesuvius in Italy", 3, "Mount_Vesuvius"),
    (4, 11, 1970, "event", "space", ["US"], None, "Apollo 13 launched", "Apollo 13 mission launches; suffers oxygen tank explosion en route to Moon", 5, "Apollo_13"),
    (4, 12, 1961, "event", "space", ["SU"], None, "Yuri Gagarin orbits Earth", "First human in space and first to orbit Earth", 5, "Yuri_Gagarin"),
    (4, 12, 1981, "event", "space", ["US"], None, "First Space Shuttle launch", "Columbia launches on STS-1, the first Space Shuttle mission", 5, "STS-1"),
    (4, 13, 1598, "event", "treaty", ["FR"], None, "Edict of Nantes", "Henry IV of France grants religious freedom to Huguenots", 4, "Edict_of_Nantes"),
    (4, 14, 1865, "event", "assassination", ["US"], None, "Lincoln shot", "President Abraham Lincoln shot by John Wilkes Booth at Ford's Theatre", 5, "Assassination_of_Abraham_Lincoln"),
    (4, 14, 1912, "event", "disaster", None, None, "Titanic hits iceberg", "RMS Titanic strikes an iceberg on her maiden voyage", 5, "Sinking_of_the_Titanic"),
    (4, 15, 1947, "event", "sports", ["US"], None, "Jackie Robinson breaks color barrier", "First African American to play in modern Major League Baseball", 5, "Jackie_Robinson"),
    (4, 16, 1963, "politics", None, ["US"], None, "MLK writes Letter from Birmingham Jail", "Martin Luther King Jr. writes his famous open letter", 5, "Letter_from_Birmingham_Jail"),
    (4, 17, 1961, "event", "invasion", ["CU"], None, "Bay of Pigs invasion", "CIA-sponsored invasion of Cuba fails", 4, "Bay_of_Pigs_Invasion"),
    (4, 18, 1906, "event", "disaster", ["US"], None, "San Francisco earthquake", "Magnitude 7.9 earthquake and fires destroy much of San Francisco", 5, "1906_San_Francisco_earthquake"),
    (4, 19, 1775, "event", "war", ["US"], None, "American Revolution begins", "Battles of Lexington and Concord", 5, "Battles_of_Lexington_and_Concord"),
    (4, 19, 1995, "event", "disaster", ["US"], None, "Oklahoma City bombing", "Truck bomb kills 168 people in Oklahoma City", 5, "Oklahoma_City_bombing"),
    (4, 20, 1999, "event", "massacre", ["US"], None, "Columbine shooting", "Two students kill 13 at Columbine High School", 5, "Columbine_High_School_massacre"),
    (4, 21, 1836, "event", "battle", ["US"], None, "Battle of San Jacinto", "Texan forces under Sam Houston defeat Santa Anna", 4, "Battle_of_San_Jacinto_(1836)"),
    (4, 22, 1970, "event", "environment", ["US"], None, "First Earth Day", "First Earth Day celebrated; 20 million Americans participate", 5, "Earth_Day"),
    (4, 23, 1564, "birth", "literature", ["GB"], None, "William Shakespeare born", "English playwright, considered the greatest writer in English", 5, "William_Shakespeare"),
    (4, 24, 1990, "event", "space", None, None, "Hubble Space Telescope launched", "Hubble launched aboard Space Shuttle Discovery", 5, "Hubble_Space_Telescope"),
    (4, 25, 1982, "event", "war", ["GB"], None, "Falklands War", "Argentina invades the Falkland Islands; UK responds", 4, "Falklands_War"),
    (4, 26, 1986, "event", "disaster", ["SU"], None, "Chernobyl disaster", "Nuclear reactor explosion at Chernobyl, Ukraine — worst nuclear accident in history", 5, "Chernobyl_disaster"),
    (4, 27, 1994, "politics", "democracy", ["ZA"], None, "First multi-racial elections in South Africa", "South Africa holds its first fully democratic elections", 5, "1994_South_African_general_election"),
    (4, 28, 1945, "event", "war", ["IT"], None, "Mussolini executed", "Italian dictator Benito Mussolini executed by partisans", 4, "Benito_Mussolini"),
    (4, 29, 2011, "event", "royal", ["GB"], None, "Royal wedding", "Prince William marries Catherine Middleton at Westminster Abbey", 4, "Wedding_of_Prince_William_and_Catherine_Middleton"),
    (4, 30, 1945, "event", "war", ["DE"], None, "Hitler dies", "Adolf Hitler commits suicide in his Berlin bunker", 5, "Death_of_Adolf_Hitler"),

    # ============== MAY ==============
    (5, 1, 1931, "event", "engineering", ["US"], None, "Empire State Building opens", "Empire State Building officially opens in New York City", 4, "Empire_State_Building"),
    (5, 2, 2011, "event", "military", ["PK"], None, "Osama bin Laden killed", "US Navy SEALs kill Osama bin Laden in Abbottabad, Pakistan", 5, "Death_of_Osama_bin_Laden"),
    (5, 3, 1947, "event", "constitution", ["JP"], None, "Japanese constitution", "Japan adopts a new pacifist constitution", 4, "Constitution_of_Japan"),
    (5, 4, 1970, "event", "protest", ["US"], None, "Kent State shootings", "Ohio National Guard kills 4 students protesting Vietnam War", 5, "Kent_State_shootings"),
    (5, 5, 1961, "event", "space", ["US"], None, "Alan Shepard first American in space", "First American in space aboard Freedom 7", 5, "Alan_Shepard"),
    (5, 6, 1937, "event", "disaster", ["US"], None, "Hindenburg disaster", "German airship LZ 129 Hindenburg catches fire and is destroyed in New Jersey", 5, "Hindenburg_disaster"),
    (5, 7, 1945, "event", "surrender", ["DE"], None, "German surrender signed", "Germany signs unconditional surrender at Allied headquarters in Reims", 5, "End_of_World_War_II_in_Europe"),
    (5, 8, 1945, "event", "war", ["DE"], None, "VE Day", "Victory in Europe Day; WWII ends in Europe", 5, "Victory_in_Europe_Day"),
    (5, 9, 1978, "death", "politics", ["IT"], None, "Aldo Moro killed", "Former Italian PM killed by Red Brigades", 4, "Aldo_Moro"),
    (5, 10, 1994, "death", "politics", ["IT"], None, "Various events", "Various events", 1, None),
    (5, 11, 1997, "event", "chess", None, None, "Deep Blue beats Kasparov", "IBM's Deep Blue defeats world chess champion Garry Kasparov", 5, "Deep_Blue_(chess_computer)"),
    (5, 12, 1949, "event", "war", None, None, "Berlin Blockade ends", "Soviet Union lifts the Berlin Blockade", 4, "Berlin_Blockade"),
    (5, 13, 1981, "event", "assassination", ["IT"], None, "Pope John Paul II shot", "Pope John Paul II shot in St. Peter's Square; survives", 4, "Attempted_assassination_of_Pope_John_Paul_II"),
    (5, 14, 1948, "politics", "independence", ["IL"], None, "Israel declares independence", "David Ben-Gurion declares the establishment of the State of Israel", 5, "Israeli_Declaration_of_Independence"),
    (5, 14, 1955, "politics", "treaty", ["PL"], None, "Warsaw Pact signed", "Soviet Union and 7 Eastern Bloc countries sign the Warsaw Pact", 4, "Warsaw_Pact"),
    (5, 15, 1940, "event", "invention", ["US"], None, "McDonald's opens", "First McDonald's restaurant opens in San Bernardino, California", 4, "McDonald%27s"),
    (5, 16, 1929, "event", "entertainment", ["US"], None, "First Academy Awards", "First Academy Awards ceremony held at the Hollywood Roosevelt Hotel", 4, "Academy_Awards"),
    (5, 17, 1954, "event", "law", ["US"], None, "Brown v. Board of Education", "US Supreme Court unanimously rules racial segregation in public schools unconstitutional", 5, "Brown_v._Board_of_Education"),
    (5, 18, 1980, "event", "volcano", ["US"], None, "Mount St. Helens erupts", "Mount St. Helens in Washington erupts, killing 57 people", 5, "1980_eruption_of_Mount_St._Helens"),
    (5, 19, 1991, "event", "protest", ["IN"], None, "Rajiv Gandhi assassinated", "Former Indian PM killed by LTTE suicide bomber", 5, "Assassination_of_Rajiv_Gandhi"),
    (5, 20, 1927, "event", "aviation", ["US"], None, "Lindbergh takes off", "Charles Lindbergh takes off from New York for the first solo transatlantic flight", 5, "Charles_Lindbergh"),
    (5, 21, 1881, "event", "medicine", ["US"], None, "Clara Barton founds Red Cross", "American Red Cross founded by Clara Barton", 4, "American_Red_Cross"),
    (5, 22, 1960, "event", "disaster", ["CL"], None, "Great Chilean earthquake", "Most powerful earthquake ever recorded (9.5 magnitude)", 5, "1960_Valdivia_earthquake"),
    (5, 23, 1934, "event", "crime", ["US"], None, "Bonnie and Clyde killed", "Outlaw couple ambushed and killed in Louisiana", 4, "Bonnie_and_Clyde"),
    (5, 24, 1844, "event", "communication", ["US"], None, "Morse sends first telegraph", "Samuel Morse sends the first telegraph message: 'What hath God wrought'", 4, "Telegraph"),
    (5, 25, 1977, "event", "film", ["US"], None, "Star Wars released", "Star Wars: A New Hope premieres in US theaters", 5, "Star_Wars_(film)"),
    (5, 26, 1896, "event", "coronation", ["RU"], None, "Nicholas II crowned", "Last Tsar of Russia crowned", 4, "Nicholas_II_of_Russia"),
    (5, 27, 1937, "event", "engineering", ["US"], None, "Golden Gate Bridge opens", "Golden Gate Bridge opens in San Francisco", 4, "Golden_Gate_Bridge"),
    (5, 28, 1934, "birth", "politics", None, None, "Various events", "Various events", 1, None),
    (5, 29, 1953, "event", "mountaineering", ["NP"], None, "Hillary and Tenzing summit Everest", "First confirmed ascent of Mount Everest", 5, "1953_British_Mount_Everest_expedition"),
    (5, 30, 1431, "death", "politics", ["FR"], None, "Joan of Arc burned at stake", "French heroine and saint burned at the stake in Rouen", 5, "Joan_of_Arc"),
    (5, 31, 1889, "event", "disaster", ["US"], None, "Johnstown Flood", "Dam failure in Pennsylvania kills 2,209 people", 4, "Johnstown_Flood"),

    # ============== JUNE ==============
    (6, 1, 1980, "event", "media", ["US"], None, "CNN launched", "Cable News Network begins broadcasting", 4, "CNN"),
    (6, 2, 1953, "event", "coronation", ["GB"], None, "Elizabeth II crowned", "Queen Elizabeth II crowned at Westminster Abbey", 4, "Coronation_of_Elizabeth_II"),
    (6, 3, 1989, "event", "politics", ["CN"], None, "Tiananmen Square crackdown", "Chinese government violently clears protesters from Tiananmen Square", 5, "Tiananmen_Square_protests_of_1989"),
    (6, 4, 1989, "event", "politics", ["PL"], None, "Polish elections", "Solidarity wins Poland's first partially free elections", 4, "Polish_legislative_election,_1989"),
    (6, 5, 1968, "event", "assassination", ["US"], None, "RFK assassinated", "Robert F. Kennedy shot at the Ambassador Hotel; dies the next day", 5, "Robert_F._Kennedy_assassination"),
    (6, 6, 1944, "event", "war", ["FR"], None, "D-Day", "Allied forces land on the beaches of Normandy in largest seaborne invasion in history", 5, "Normandy_landings"),
    (6, 7, 1942, "event", "war", None, None, "Battle of Midway begins", "US Navy defeats Japanese fleet in the Pacific turning point", 5, "Battle_of_Midway"),
    (6, 8, 1949, "event", "literature", ["GB"], None, "1984 published", "George Orwell's dystopian novel published", 4, "Nineteen_Eighty-Four"),
    (6, 9, 1934, "birth", "entertainment", ["US"], None, "Donald Duck debuts", "Donald Duck appears in the animated short 'The Wise Little Hen'", 4, "Donald_Duck"),
    (6, 10, 1940, "event", "war", None, None, "Italy enters WWII", "Italy declares war on France and Britain", 3, "Military_history_of_Italy_during_World_War_II"),
    (6, 11, 1963, "event", "disaster", ["VN"], None, "Buddhist crisis", "Buddhist monk protests self-immolation in South Vietnam", 4, "Buddhist_crisis"),
    (6, 12, 1967, "event", "law", ["US"], None, "Loving v. Virginia", "US Supreme Court strikes down laws banning interracial marriage", 4, "Loving_v._Virginia"),
    (6, 13, 1971, "event", "media", ["US"], None, "Pentagon Papers published", "NY Times begins publishing the Pentagon Papers", 4, "Pentagon_Papers"),
    (6, 14, 1922, "event", "politics", ["US"], None, "Warren Harding's radio speech", "Various events", 2, None),
    (6, 15, 1215, "event", "politics", ["GB"], None, "Magna Carta signed", "King John of England seals the Magna Carta at Runnymede", 5, "Magna_Carta"),
    (6, 16, 1963, "event", "space", ["SU"], None, "First woman in space", "Valentina Tereshkova becomes first woman in space aboard Vostok 6", 5, "Valentina_Tereshkova"),
    (6, 17, 1972, "event", "crime", ["US"], None, "Watergate break-in", "Five men arrested for breaking into DNC headquarters at the Watergate complex", 5, "Watergate_scandal"),
    (6, 18, 1815, "battle", None, ["BE"], None, "Battle of Waterloo", "Napoleon defeated by British and Prussian forces, ending Napoleonic Wars", 5, "Battle_of_Waterloo"),
    (6, 19, 1865, "event", "emancipation", ["US"], None, "Juneteenth", "Enslaved people in Texas learn they are free, two months after Emancipation Proclamation", 5, "Juneteenth"),
    (6, 20, 1975, "event", "film", ["US"], None, "Jaws released", "Steven Spielberg's Jaws released; first summer blockbuster", 4, "Jaws_(film)"),
    (6, 21, 1788, "event", "constitution", ["US"], None, "US Constitution ratified", "New Hampshire becomes the 9th state to ratify, making the Constitution effective", 5, "Constitution_of_the_United_States"),
    (6, 22, 1941, "event", "war", ["DE"], None, "Operation Barbarossa", "Nazi Germany invades the Soviet Union — largest military operation in history", 5, "Operation_Barber_the_Red"),
    (6, 23, 1972, "event", "law", ["US"], None, "Title IX enacted", "US law prohibiting sex discrimination in education", 4, "Title_IX"),
    (6, 24, 1497, "event", "exploration", None, None, "John Cabot reaches North America", "Italian explorer John Cabot lands in Newfoundland", 3, "John_Cabot"),
    (6, 25, 1950, "event", "war", ["KP"], None, "Korean War begins", "North Korea invades South Korea", 5, "Korean_War"),
    (6, 26, 1945, "event", "politics", ["US"], None, "UN Charter signed", "United Nations Charter signed in San Francisco", 4, "United_Nations_Charter"),
    (6, 27, 1950, "event", "war", ["KP"], None, "Various events", "Various events", 1, None),
    (6, 28, 1914, "event", "assassination", ["BA"], None, "Archduke Franz Ferdinand assassinated", "Austrian Archduke assassinated in Sarajevo; triggers WWI", 5, "Assassination_of_Archduke_Franz_Ferdinand"),
    (6, 29, 2007, "event", "technology", ["US"], None, "iPhone released", "Apple iPhone released, revolutionizing smartphones", 5, "iPhone"),
    (6, 30, 1936, "event", "literature", ["US"], None, "Gone with the Wind published", "Margaret Mitchell's novel published", 4, "Gone_with_the_Wind_(novel)"),

    # ============== JULY ==============
    (7, 1, 1997, "politics", "handover", ["CN", "HK"], None, "Hong Kong returned to China", "Hong Kong transferred from UK to China after 156 years", 5, "Transfer_of_sovereignty_over_Hong_Kong"),
    (7, 2, 1937, "disappearance", None, ["US"], None, "Amelia Earhart disappears", "Pioneering aviator disappears over the Pacific", 4, "Amelia_Earhart"),
    (7, 3, 1948, "politics", "independence", ["US"], None, "Cleveland's Independence Day off", "Various events", 2, None),
    (7, 4, 1776, "politics", "independence", ["US"], None, "US Declaration of Independence", "Continental Congress adopts the Declaration of Independence", 5, "United_States_Declaration_of_Independence"),
    (7, 5, 1946, "event", "fashion", ["FR"], None, "Bikini introduced", "Louis Réard introduces the modern bikini at a Paris fashion show", 4, "Bikini"),
    (7, 6, 1942, "event", "war", None, None, "Anne Frank goes into hiding", "Anne Frank and her family go into hiding in Amsterdam", 4, "Anne_Frank"),
    (7, 7, 1941, "event", "archaeology", ["US"], None, "Iceman found? No — various", "Various events", 1, None),
    (7, 8, 1947, "event", "ufo", ["US"], None, "Roswell incident", "Alleged UFO crash near Roswell, New Mexico", 4, "Roswell_UFO_incident"),
    (7, 9, 1943, "event", "war", ["IT"], None, "Allied invasion of Sicily", "Operation Husky begins", 3, "Allied_invasion_of_Sicily"),
    (7, 10, 1940, "event", "war", ["GB"], None, "Battle of Britain begins", "Luftwaffe begins sustained bombing campaign against Britain", 4, "Battle_of_Britain"),
    (7, 11, 1979, "disaster", "space", None, None, "Skylab re-enters atmosphere", "Skylab space station breaks up over Australia", 3, "Skylab"),
    (7, 12, 1962, "event", "music", ["GB"], None, "Rolling Stones debut", "The Rolling Stones play their first gig at the Marquee Club in London", 4, "The_Rolling_Stones"),
    (7, 13, 1985, "event", "music", ["GB", "US"], None, "Live Aid concert", "Global benefit concert for Ethiopian famine relief", 5, "Live_Aid"),
    (7, 14, 1789, "event", "revolution", ["FR"], None, "Storming of the Bastille", "Parisian revolutionaries storm the Bastille, igniting the French Revolution", 5, "Storming_of_the_Bastille"),
    (7, 15, 1971, "event", "media", ["US"], None, "Pentagon Papers case", "Supreme Court rules for NYT in Pentagon Papers case", 3, "New_York_Times_Co._v._United_States"),
    (7, 16, 1945, "event", "science", ["US"], None, "Trinity nuclear test", "First detonation of a nuclear weapon, in New Mexico desert", 5, "Trinity_(nuclear_test)"),
    (7, 17, 1918, "death", "royal", ["RU"], None, "Romanov family executed", "Tsar Nicholas II and his family executed by Bolsheviks in Yekaterinburg", 5, "Execution_of_the_Romanov_family"),
    (7, 18, 1969, "event", "music", ["US"], None, "Chappaquiddick incident", "Ted Kennedy's car accident at Chappaquiddick; Mary Jo Kopechne dies", 3, "Chappaquiddick_incident"),
    (7, 19, 1848, "event", "women", ["US"], None, "Seneca Falls Convention", "First women's rights convention held in Seneca Falls, NY", 4, "Seneca_Falls_Convention"),
    (7, 19, 1969, "event", "space", None, None, "Apollo 11 lands on Moon", "Neil Armstrong becomes first human to walk on the Moon", 5, "Apollo_11"),
    (7, 20, 1969, "event", "space", None, None, "Moon landing", "Apollo 11 lands on the Moon; Armstrong takes 'one small step'", 5, "Apollo_11"),
    (7, 21, 1925, "event", "law", ["US"], None, "Scopes Monkey Trial", "Tennessee v. John Scopes begins; trial of a teacher for teaching evolution", 4, "Scopes_Trial"),
    (7, 22, 1933, "event", "crime", ["US"], None, "Wiley Post flies solo around world", "First solo flight around the world completed", 4, "Wiley_Post"),
    (7, 23, 1967, "event", "race", ["US"], None, "Detroit riots", "12th Street Riot in Detroit; 43 dead, 1,189 injured", 3, "1967_Detroit_riot"),
    (7, 24, 1847, "discovery", None, ["US"], None, "Brigham Young enters Salt Lake Valley", "Mormon leader enters what becomes Salt Lake City, Utah", 4, "Salt_Lake_City"),
    (7, 25, 1978, "event", "medical", ["GB"], None, "First test-tube baby born", "Louise Brown, first baby conceived via in vitro fertilization, born in England", 5, "Louise_Brown"),
    (7, 26, 1947, "event", "politics", ["US"], None, "National Security Act signed", "Creates the CIA, National Security Council, and Department of Defense", 3, "National_Security_Act_of_1947"),
    (7, 27, 1996, "event", "disaster", ["US"], None, "Centennial Olympic Park bombing", "Bombing at Atlanta Olympics kills 2 and injures 111", 4, "Centennial_Olympic_Park_bombing"),
    (7, 28, 1945, "event", "aviation", ["US"], None, "B-25 crashes into Empire State Building", "Army bomber crashes into Empire State Building in fog", 3, "1945_Empire_State_Building_B-25_crash"),
    (7, 29, 1958, "event", "politics", ["US"], None, "NASA established", "National Aeronautics and Space Administration (NASA) established", 4, "NASA"),
    (7, 30, 1930, "event", "sports", None, None, "First FIFA World Cup", "First FIFA World Cup begins in Uruguay", 5, "1930_FIFA_World_Cup"),
    (7, 31, 1971, "event", "space", ["US"], None, "Apollo 15 lands on Moon", "David Scott and James Irwin land on the Moon", 4, "Apollo_15"),

    # ============== AUGUST ==============
    (8, 1, 1966, "event", "massacre", ["US"], None, "Charles Whitman rampage", "University of Texas tower shooting kills 16 and injures 31", 4, "University_of_Texas_tower_shooting"),
    (8, 2, 1990, "event", "war", ["IQ"], None, "Iraq invades Kuwait", "Iraqi forces invade Kuwait, triggering Gulf War", 5, "Invasion_of_Kuwait"),
    (8, 3, 1492, "event", "exploration", None, None, "Columbus sets sail", "Christopher Columbus sets sail from Spain, leading to European discovery of the Americas", 5, "Voyages_of_Christopher_Columbus"),
    (8, 4, 1944, "event", "war", ["NL"], None, "Anne Frank captured", "Anne Frank and family captured by Gestapo in Amsterdam", 4, "Anne_Frank"),
    (8, 5, 1962, "event", "entertainment", ["US"], None, "Marilyn Monroe dies", "American actress, model, and singer dies at age 36", 5, "Marilyn_Monroe"),
    (8, 6, 1945, "event", "war", ["JP"], None, "Hiroshima atomic bomb", "US drops atomic bomb on Hiroshima, Japan", 5, "Atomic_bombings_of_Hiroshima_and_Nagasaki"),
    (8, 7, 1959, "event", "exploration", ["US"], None, "Explorer 6 photos Earth", "First satellite to send back photos of Earth from space", 4, "Explorer_6"),
    (8, 8, 1945, "event", "law", None, None, "London Charter signed", "Sets framework for Nuremberg trials", 3, "London_Charter_of_the_International_Military_Tribunal"),
    (8, 9, 1945, "event", "war", ["JP"], None, "Nagasaki atomic bomb", "Second atomic bomb dropped on Nagasaki, Japan", 5, "Atomic_bombings_of_Hiroshima_and_Nagasaki"),
    (8, 10, 1793, "event", "culture", ["FR"], None, "Louvre opens", "Musée du Louvre opens to the public as a museum", 4, "Louvre"),
    (8, 11, 1999, "event", "astronomy", ["DE", "US"], None, "Last total solar eclipse of 20th century", "Total solar eclipse visible across Europe and Asia", 3, "Solar_eclipse_of_August_11,_1999"),
    (8, 12, 1877, "event", "invention", ["US"], None, "Edison patents the phonograph", "First device to record and play back sound", 4, "Phonograph"),
    (8, 13, 1961, "event", "engineering", ["DE"], None, "Berlin Wall built", "East Germany begins building the Berlin Wall", 5, "Berlin_Wall"),
    (8, 14, 1947, "politics", "independence", ["PK", "IN"], None, "Pakistan independence", "Pakistan gains independence from British India", 5, "Independence_of_Pakistan"),
    (8, 15, 1969, "event", "music", ["US"], None, "Woodstock begins", "Woodstock Festival opens in Bethel, New York", 5, "Woodstock"),
    (8, 16, 1977, "death", "music", ["US"], None, "Elvis Presley dies", "King of Rock and Roll dies at age 42", 5, "Elvis_Presley"),
    (8, 17, 1943, "event", "war", ["DE"], None, "Schweinfurt raids", "First American bombing raid on Germany", 3, "Schweinfurt%E2%80%93Regensburg_mission"),
    (8, 18, 1920, "politics", "rights", ["US"], None, "19th Amendment ratified", "Women's suffrage amendment ratified in the United States", 5, "Nineteenth_Amendment_to_the_United_States_Constitution"),
    (8, 19, 1991, "event", "revolution", ["SU"], None, "Soviet coup attempt", "Hardliners attempt coup against Gorbachev; fails within 3 days", 5, "1991_Soviet_coup_attempt"),
    (8, 20, 1968, "event", "war", ["SU"], None, "Soviet invasion of Czechoslovakia", "Warsaw Pact troops invade Czechoslovakia to crush the Prague Spring", 4, "Warsaw_Pact_invasion_of_Czechoslovakia"),
    (8, 21, 1959, "politics", "statehood", ["US"], None, "Hawaii becomes a state", "Hawaii admitted as the 50th US state", 3, "Hawaii"),
    (8, 22, 1654, "event", "law", ["BR"], None, "First Jewish congregation in US", "First Jewish congregation in North America established in New Amsterdam", 2, "Congregation_Shearith_Israel"),
    (8, 23, 1973, "event", "crime", ["SE"], None, "Bank robbery in Stockholm", "Bank robbery in Stockholm that gave rise to 'Stockholm syndrome'", 3, "Norrmalmstorg_robbery"),
    (8, 24, 1814, "event", "war", ["US"], None, "Washington burned", "British forces burn Washington, DC during War of 1812", 4, "Burning_of_Washington"),
    (8, 25, 1944, "event", "war", ["FR"], None, "Paris liberated", "Allied forces liberate Paris from Nazi occupation", 5, "Liberation_of_Paris"),
    (8, 26, 1920, "politics", "rights", ["US"], None, "19th Amendment takes effect", "Women's right to vote takes effect in the United States", 5, "Nineteenth_Amendment_to_the_United_States_Constitution"),
    (8, 27, 1883, "event", "volcano", ["ID"], None, "Krakatoa erupts", "Krakatoa volcano erupts with massive force; kills 36,000", 5, "1883_eruption_of_Krakatoa"),
    (8, 28, 1963, "event", "civil rights", ["US"], None, "March on Washington", "MLK delivers 'I Have a Dream' speech to 250,000 at the Lincoln Memorial", 5, "March_on_Washington_for_Jobs_and_Freedom"),
    (8, 29, 2005, "event", "disaster", ["US"], None, "Hurricane Katrina", "Hurricane Katrina strikes the US Gulf Coast, devastating New Orleans", 5, "Hurricane_Katrina"),
    (8, 30, 1967, "politics", "constitution", None, None, "Thurgood Marshall confirmed", "First African American Supreme Court Justice confirmed", 4, "Thurgood_Marshall"),
    (8, 31, 1997, "death", "royal", ["FR", "GB"], None, "Princess Diana dies", "Princess of Wales dies in Paris car crash", 5, "Death_of_Diana,_Princess_of_Wales"),

    # ============== SEPTEMBER ==============
    (9, 1, 1939, "event", "war", ["PL"], None, "Germany invades Poland", "Germany invades Poland, starting World War II in Europe", 5, "Invasion_of_Poland"),
    (9, 2, 1945, "event", "war", ["JP"], None, "V-J Day", "Japan signs surrender, ending World War II", 5, "Victory_over_Japan_Day"),
    (9, 3, 1783, "treaty", None, ["US", "GB"], None, "Treaty of Paris (1783)", "American Revolutionary War officially ends", 4, "Treaty_of_Paris_(1783)"),
    (9, 4, 1888, "event", "invention", ["US"], None, "George Eastman patents Kodak", "Kodak roll-film camera patented", 4, "George_Eastman"),
    (9, 5, 1972, "event", "terrorism", ["DE"], None, "Munich Olympics massacre", "Palestinian terrorists kill 11 Israeli athletes", 5, "Munich_massacre"),
    (9, 6, 1901, "event", "assassination", ["US"], None, "McKinley shot", "President William McKinley shot at Pan-American Exposition", 4, "Assassination_of_William_McKinley"),
    (9, 7, 1940, "event", "war", ["GB"], None, "Blitz begins", "Germany begins sustained bombing of London", 4, "The_Blitz"),
    (9, 8, 1974, "event", "politics", ["US"], None, "Ford pardons Nixon", "President Gerald Ford pardons Richard Nixon for Watergate", 4, "Pardon_of_Richard_Nixon"),
    (9, 9, 1976, "death", "politics", ["CN"], None, "Mao Zedong dies", "Chairman of the Communist Party of China", 5, "Mao_Zedong"),
    (9, 10, 1846, "event", "invention", ["US"], None, "Sewing machine patented", "Elias Howe receives patent for the sewing machine", 3, "Elias_Howe"),
    (9, 11, 2001, "event", "terrorism", ["US"], None, "September 11 attacks", "Al-Qaeda hijack 4 planes; 2,977 killed in NYC, Pentagon, and PA", 5, "September_11_attacks"),
    (9, 12, 1940, "event", "archaeology", ["FR"], None, "Lascaux cave paintings discovered", "Prehistoric cave paintings found in southwestern France", 4, "Lascaux"),
    (9, 13, 1788, "event", "politics", ["US"], None, "US Constitution adopted", "Constitutional Convention adopts the US Constitution", 4, "Constitution_of_the_United_States"),
    (9, 14, 1814, "event", "music", ["US"], None, "Star-Spangled Banner written", "Francis Scott Key writes the poem that becomes the US national anthem", 5, "The_Star-Spangled_Banner"),
    (9, 15, 1963, "event", "civil rights", ["US"], None, "Birmingham church bombing", "Bombing of 16th Street Baptist Church kills 4 young girls", 5, "16th_Street_Baptist_Church_bombing"),
    (9, 16, 1620, "event", "exploration", ["US"], None, "Mayflower sets sail", "Mayflower sets sail from England with Pilgrims bound for America", 4, "Mayflower"),
    (9, 17, 1977, "event", "photography", ["US"], None, "Voyager 1 photo", "Voyager 1 takes the Pale Blue Dot photo of Earth", 4, "Pale_Blue_Dot"),
    (9, 18, 1973, "event", "sports", None, None, "Battle of the sexes", "Billie Jean King defeats Bobby Riggs in tennis match", 3, "Battle_of_the_Sexes_(tennis)"),
    (9, 19, 1985, "event", "disaster", ["MX"], None, "Mexico City earthquake", "Magnitude 8.1 earthquake kills 9,000+", 5, "1985_Mexico_City_earthquake"),
    (9, 20, 1519, "event", "exploration", None, None, "Magellan sets sail", "Ferdinand Magellan's expedition sets sail to circumnavigate the globe", 4, "Ferdinand_Magellan"),
    (9, 21, 1937, "event", "literature", ["GB"], None, "Hobbit published", "J.R.R. Tolkien publishes The Hobbit", 4, "The_Hobbit"),
    (9, 22, 1927, "event", "boxing", ["US"], None, "Tunney-Dempsey fight", "Gene Tunney defeats Jack Dempsey in controversial 'Long Count' fight", 4, "Gene_Tunney_vs._Jack_Dempsey"),
    (9, 23, 1846, "event", "astronomy", ["DE"], None, "Neptune discovered", "Johann Galle discovers Neptune based on Le Verrier's calculations", 5, "Neptune"),
    (9, 24, 1890, "religion", "founding", ["US"], None, "Church of Jesus Christ of LDS ends polygamy", "Wilford Woodruff manifesto", 3, "1890_Manifesto"),
    (9, 25, 1957, "event", "civil rights", ["US"], None, "Little Rock Nine", "Nine African American students integrate Little Rock Central High School", 4, "Little_Rock_Nine"),
    (9, 26, 1960, "event", "politics", ["US"], None, "First televised presidential debate", "Kennedy vs. Nixon, watched by 70 million", 4, "Kennedy%E2%80%93Nixon_debates"),
    (9, 27, 1961, "politics", "independence", ["SL"], None, "Sierra Leone independence", "Sierra Leone gains independence from UK", 3, "Independence_of_Sierra_Leone"),
    (9, 28, 1928, "event", "medicine", ["US"], None, "Penicillin discovered", "Alexander Fleming discovers penicillin", 5, "Alexander_Fleming"),
    (9, 29, 1938, "event", "treaty", ["GB", "DE", "IT", "FR"], None, "Munich Agreement", "Britain and France allow Nazi Germany to annex Sudetenland", 4, "Munich_Agreement"),
    (9, 30, 1955, "death", "film", ["US"], None, "James Dean dies", "Actor killed in car crash at age 24", 4, "James_Dean"),

    # ============== OCTOBER ==============
    (10, 1, 1908, "event", "invention", ["US"], None, "Ford Model T introduced", "Ford Model T unveiled; the 'car for the masses'", 5, "Ford_Model_T"),
    (10, 2, 1967, "event", "civil rights", ["US"], None, "Thurgood Marshall on SCOTUS", "Sworn in as first African American Supreme Court Justice", 4, "Thurgood_Marshall"),
    (10, 3, 1990, "politics", "unification", ["DE"], None, "German reunification", "East and West Germany officially reunite", 5, "German_reunification"),
    (10, 4, 1957, "event", "space", ["SU"], None, "Sputnik 1 launched", "First artificial satellite launched by Soviet Union", 5, "Sputnik_1"),
    (10, 5, 2011, "death", "technology", ["US"], None, "Steve Jobs dies", "Apple co-founder dies at 56 of pancreatic cancer", 5, "Steve_Jobs"),
    (10, 6, 1973, "event", "war", ["IL", "SY"], None, "Yom Kippur War begins", "Egypt and Syria launch surprise attack on Israel", 5, "Yom_Kippur_War"),
    (10, 7, 2001, "event", "war", ["AF"], None, "US invasion of Afghanistan begins", "Operation Enduring Freedom begins", 5, "War_in_Afghanistan_(2001%E2%80%932021)"),
    (10, 8, 1871, "event", "disaster", ["US"], None, "Great Chicago Fire", "Fire destroys much of Chicago, kills 300, leaves 100,000 homeless", 5, "Great_Chicago_Fire"),
    (10, 9, 1967, "death", "politics", ["AR"], None, "Che Guevara executed", "Argentine revolutionary captured and executed in Bolivia", 5, "Che_Guevara"),
    (10, 10, 1973, "event", "politics", ["US"], None, "Agnew resigns", "Spiro Agnew resigns as US Vice President", 3, "Spiro_Agnew"),
    (10, 11, 1975, "event", "sports", ["US"], None, "Saturday Night Live premieres", "SNL debuts on NBC", 4, "Saturday_Night_Live"),
    (10, 12, 1492, "event", "exploration", None, None, "Columbus reaches Americas", "Columbus lands in the Bahamas, the first European to reach the Americas (controversial given Vikings)", 5, "Christopher_Columbus"),
    (10, 13, 1775, "event", "military", ["US"], None, "US Navy founded", "Continental Congress establishes the Continental Navy", 3, "United_States_Navy"),
    (10, 14, 1947, "event", "aviation", ["US"], None, "Chuck Yeager breaks sound barrier", "Bell X-1 becomes first crewed aircraft to exceed the speed of sound", 5, "Chuck_Yeager"),
    (10, 15, 1969, "event", "protest", ["US"], None, "Vietnam Moratorium", "Largest antiwar rally in US history; 2 million demonstrate", 4, "Moratorium_to_End_the_War_in_Vietnam"),
    (10, 16, 1846, "event", "medical", ["US"], None, "First public demonstration of ether anesthesia", "William T.G. Morton demonstrates ether anesthesia at Massachusetts General Hospital", 4, "William_T._G._Morton"),
    (10, 17, 1989, "event", "disaster", ["US"], None, "Loma Prieta earthquake", "Earthquake hits San Francisco Bay Area during World Series", 4, "1989_Loma_Prieta_earthquake"),
    (10, 18, 1922, "event", "media", ["GB"], None, "BBC founded", "British Broadcasting Corporation founded", 4, "BBC"),
    (10, 19, 1987, "event", "economics", None, None, "Black Monday stock crash", "Dow Jones drops 22.6% — largest single-day percentage decline", 5, "Black_Monday_(1987)"),
    (10, 20, 1973, "event", "politics", ["AU"], None, "Sydney Opera House opens", "Sydney Opera House officially opened by Queen Elizabeth II", 4, "Sydney_Opera_House"),
    (10, 21, 1959, "event", "literature", ["US"], None, "Various events", "Various events", 1, None),
    (10, 22, 1962, "event", "politics", ["US"], None, "Cuban Missile Crisis begins", "JFK addresses nation on Soviet missiles in Cuba", 5, "Cuban_Missile_Crisis"),
    (10, 23, 1947, "event", "geopolitics", ["PK"], None, "Partition of India", "First Indo-Pakistani War begins; massive migration follows partition", 5, "Partition_of_India"),
    (10, 24, 1945, "event", "law", None, None, "UN Charter takes effect", "United Nations officially comes into existence", 4, "United_Nations"),
    (10, 25, 1415, "event", "war", ["FR"], None, "Battle of Agincourt", "English forces defeat French in Hundred Years' War", 4, "Battle_of_Agincourt"),
    (10, 26, 1863, "event", "association", ["GB"], None, "Football Association founded", "First football association in the world founded in England", 4, "The_Football_Association"),
    (10, 27, 1961, "event", "space", None, None, "Saur Revolution in Afghanistan", "Soviet-backed coup in Afghanistan", 4, "Saur_Revolution"),
    (10, 28, 1886, "event", "engineering", ["US"], None, "Statue of Liberty dedicated", "Dedication ceremony for the Statue of Liberty", 5, "Statue_of_Liberty"),
    (10, 29, 1929, "event", "economics", ["US"], None, "Black Tuesday", "Stock market crash begins the Great Depression", 5, "Wall_Street_Crash_of_1929"),
    (10, 30, 1938, "event", "radio", ["US"], None, "War of the Worlds broadcast", "Orson Welles' radio broadcast causes panic", 4, "The_War_of_the_Worlds_(radio_drama)"),
    (10, 31, 1517, "event", "religion", None, "christian", "Luther's 95 Theses", "Martin Luther posts 95 Theses on church door, sparking the Reformation", 5, "Ninety-five_Theses"),

    # ============== NOVEMBER ==============
    (11, 1, 1950, "event", "assassination", ["PR"], None, "Attempted assassination of Truman", "Puerto Rican nationalists attempt to assassinate President Truman", 3, "Attempted_assassination_of_Harry_S._Truman"),
    (11, 2, 1947, "event", "aviation", ["US"], None, "Spruce Goose flies", "Howard Hughes' massive wooden cargo plane makes its only flight", 4, "Hughes_H-4_Hercules"),
    (11, 3, 1957, "event", "space", ["SU"], None, "Laika in space", "Soviet dog Laika becomes first animal to orbit Earth aboard Sputnik 2", 4, "Laika"),
    (11, 4, 1979, "event", "terrorism", ["IR"], None, "Iran hostage crisis begins", "Iranian students seize the US Embassy in Tehran", 5, "Iran_hostage_crisis"),
    (11, 5, 1605, "event", "crime", ["GB"], None, "Gunpowder Plot", "Guy Fawkes caught trying to blow up Parliament", 4, "Gunpowder_Plot"),
    (11, 6, 1860, "politics", "election", ["US"], None, "Lincoln elected president", "Abraham Lincoln elected 16th US President", 5, "1860_United_States_presidential_election"),
    (11, 7, 1917, "politics", "revolution", ["RU"], None, "October Revolution", "Bolshevik Revolution begins in Russia", 5, "October_Revolution"),
    (11, 8, 1895, "event", "science", ["DE"], None, "Roentgen discovers X-rays", "Wilhelm Conrad Röntgen discovers X-rays", 5, "Wilhelm_Conrad_R%C3%B6ntgen"),
    (11, 9, 1938, "event", "persecution", ["DE"], None, "Kristallnacht", "Nazi pogrom against Jews throughout Germany and Austria", 5, "Kristallnacht"),
    (11, 10, 1775, "event", "military", ["US"], None, "US Marine Corps founded", "Continental Marines established at Tun Tavern, Philadelphia", 4, "United_States_Marine_Corps"),
    (11, 11, 1918, "event", "war", ["FR"], None, "WWI Armistice", "Armistice signed ending fighting in WWI on the Western Front", 5, "Armistice_of_11_November_1918"),
    (11, 12, 1940, "event", "war", ["GB"], None, "Battle of Taranto", "British torpedo bombers cripple Italian fleet", 3, "Battle_of_Taranto"),
    (11, 13, 2015, "event", "terrorism", ["FR"], None, "Paris attacks", "Coordinated terrorist attacks across Paris kill 130", 5, "November_2015_Paris_attacks"),
    (11, 14, 1851, "event", "literature", ["GB"], None, "Moby-Dick published", "Herman Melville's novel published", 4, "Moby-Dick"),
    (11, 15, 1920, "event", "war", None, None, "First meeting of League of Nations", "League of Nations holds first meeting in Geneva", 3, "League_of_Nations"),
    (11, 16, 1903, "event", "geopolitics", ["PA"], None, "Panama separates from Colombia", "With US support, Panama declares independence from Colombia", 3, "Panama"),
    (11, 17, 1970, "event", "software", ["US"], None, "Unix time begins", "Unix epoch begins at 00:00:00 UTC", 3, "Unix_time"),
    (11, 18, 1928, "event", "media", ["US"], None, "Mickey Mouse in Steamboat Willie", "Steamboat Willie released; Mickey Mouse debuts", 5, "Steamboat_Willie"),
    (11, 19, 1863, "event", "war", ["US"], None, "Gettysburg Address", "Lincoln delivers the Gettysburg Address", 5, "Gettysburg_Address"),
    (11, 20, 1945, "event", "law", None, None, "Nuremberg trials begin", "Trial of major Nazi war criminals begins", 5, "Nuremberg_trials"),
    (11, 21, 1783, "event", "aviation", ["FR"], None, "First manned free flight", "Jean-François Pilâtre de Rozier makes first manned free flight in a Montgolfier balloon", 4, "Montgolfier_brothers"),
    (11, 22, 1963, "event", "assassination", ["US"], None, "JFK assassinated", "President John F. Kennedy shot in Dallas, Texas", 5, "Assassination_of_John_F._Kennedy"),
    (11, 23, 1936, "event", "media", ["US"], None, "Life magazine debuts", "Henry Luce launches Life magazine", 3, "Life_(magazine)"),
    (11, 24, 1859, "event", "science", ["GB"], None, "Origin of Species published", "Charles Darwin publishes On the Origin of Species", 5, "On_the_Origin_of_Species"),
    (11, 25, 2015, "event", "conflict", ["TR"], None, "Russian Su-24 shot down", "Turkish fighter jet shoots down Russian Su-24 bomber", 3, "2015_Russian_Su-24_shootdown"),
    (11, 26, 2008, "event", "terrorism", ["IN"], None, "Mumbai attacks", "10 Pakistani terrorists attack multiple sites in Mumbai; 166 dead", 5, "2008_Mumbai_attacks"),
    (11, 27, 1095, "event", "religion", None, "christian", "Pope Urban II calls First Crusade", "Speech launching the First Crusade at Council of Clermont", 4, "Pope_Urban_II"),
    (11, 28, 1520, "event", "exploration", None, None, "Magellan enters Pacific", "Magellan's expedition rounds Cape Horn and enters the Pacific Ocean", 4, "Ferdinand_Magellan"),
    (11, 29, 1947, "politics", "partition", ["PS", "IL"], None, "UN Partition Plan for Palestine", "UN General Assembly votes to partition Palestine", 4, "United_Nations_Partition_Plan_for_Palestine"),
    (11, 30, 1939, "event", "war", ["SU"], None, "Soviet invasion of Finland", "Winter War begins as USSR invades Finland", 4, "Winter_War"),

    # ============== DECEMBER ==============
    (12, 1, 1955, "event", "civil rights", ["US"], None, "Rosa Parks refuses to give up seat", "Rosa Parks arrested in Montgomery, Alabama; bus boycott begins", 5, "Rosa_Parks"),
    (12, 2, 1942, "event", "science", ["US"], None, "First self-sustaining nuclear chain reaction", "Enrico Fermi leads team to achieve first controlled nuclear chain reaction at University of Chicago", 5, "Chicago_Pile-1"),
    (12, 3, 1967, "event", "medical", ["ZA"], None, "First heart transplant", "Dr. Christiaan Barnard performs first successful human heart transplant", 5, "Christiaan_Barnard"),
    (12, 4, 1786, "event", "music", ["AT"], None, "Various events", "Various events", 1, None),
    (12, 5, 1933, "event", "law", ["US"], None, "21st Amendment", "21st Amendment ratified, ending Prohibition in the US", 4, "Twenty-first_Amendment_to_the_United_States_Constitution"),
    (12, 6, 1865, "event", "civil rights", ["US"], None, "13th Amendment ratified", "Abolishes slavery in the United States", 5, "Thirteenth_Amendment_to_the_United_States_Constitution"),
    (12, 7, 1941, "event", "war", ["US", "JP"], None, "Pearl Harbor", "Japanese attack on Pearl Harbor brings US into WWII", 5, "Attack_on_Pearl_Harbor"),
    (12, 8, 1980, "death", "music", ["GB"], None, "John Lennon shot", "Former Beatle shot and killed in New York City", 5, "Death_of_John_Lennon"),
    (12, 9, 1979, "event", "health", ["US"], None, "Smallpox eradicated", "WHO certifies the global eradication of smallpox", 5, "Smallpox"),
    (12, 10, 1901, "event", "literature", ["SE"], None, "First Nobel Prizes", "First Nobel Prizes awarded", 4, "Nobel_Prize"),
    (12, 11, 1941, "event", "war", ["DE"], None, "Hitler declares war on US", "Following Pearl Harbor, Hitler declares war on the United States", 4, "Declaration_by_United_Nations"),
    (12, 12, 1870, "event", "civil rights", ["US"], None, "Joseph Hayne Rainey sworn in", "First African American in the US House of Representatives", 4, "Joseph_Hayne_Rainey"),
    (12, 13, 2003, "event", "war", ["IQ"], None, "Saddam Hussein captured", "Former Iraqi dictator captured near Tikrit", 5, "Capture_of_Saddam_Hussein"),
    (12, 14, 1799, "death", "politics", ["US"], None, "George Washington dies", "First President of the United States dies at 67", 5, "George_Washington"),
    (12, 15, 1961, "event", "war", ["IL"], None, "Various events", "Various events", 1, None),
    (12, 16, 1944, "event", "war", ["BE"], None, "Battle of the Bulge begins", "Germany launches last major offensive on Western Front", 5, "Battle_of_the_Bulge"),
    (12, 17, 1903, "event", "aviation", ["US"], None, "Wright Brothers' first flight", "First powered, sustained, and controlled heavier-than-air flight at Kitty Hawk", 5, "Wright_brothers"),
    (12, 18, 1865, "event", "law", ["US"], None, "13th Amendment ratified", "Abolishes slavery throughout the United States", 5, "Thirteenth_Amendment_to_the_United_States_Constitution"),
    (12, 19, 1998, "event", "politics", ["US"], None, "Clinton impeached", "US House impeaches President Bill Clinton", 4, "Impeachment_of_Bill_Clinton"),
    (12, 20, 1989, "event", "war", ["PA"], None, "US invades Panama", "Operation Just Cause begins", 3, "United_States_invasion_of_Panama"),
    (12, 21, 1968, "event", "space", ["US"], None, "Apollo 8 launches", "First crewed mission to orbit the Moon", 5, "Apollo_8"),
    (12, 22, 1944, "event", "war", ["DE"], None, "Battle of the Bulge", "Largest battle fought by US in WWII", 5, "Battle_of_the_Bulge"),
    (12, 23, 1823, "event", "diplomacy", ["US"], None, "A Visit from St. Nicholas published", "'Twas the Night Before Christmas' poem published", 4, "A_Visit_from_St._Nicholas"),
    (12, 24, 1968, "event", "space", None, None, "Apollo 8 Earthrise", "Astronauts on Apollo 8 take the iconic 'Earthrise' photo", 5, "Earthrise"),
    (12, 25, 1991, "event", "politics", ["SU"], None, "Mikhail Gorbachev resigns", "Last leader of the Soviet Union resigns; USSR dissolves the next day", 5, "Dissolution_of_the_Soviet_Union"),
    (12, 26, 2004, "event", "disaster", None, None, "Indian Ocean tsunami", "Magnitude 9.1 earthquake triggers tsunami killing 230,000+ across 14 countries", 5, "2004_Indian_Ocean_earthquake_and_tsunami"),
    (12, 27, 1945, "event", "economics", None, None, "World Bank established", "International Bank for Reconstruction and Development begins operations", 4, "World_Bank"),
    (12, 28, 1895, "event", "film", ["FR"], None, "First public film screening", "Lumière brothers hold first commercial film screening in Paris", 5, "Auguste_and_Louis_Lumi%C3%A8re"),
    (12, 29, 1845, "politics", "statehood", ["US"], None, "Texas admitted to Union", "Texas becomes the 28th US state", 4, "Texas"),
    (12, 30, 1922, "politics", "founding", ["SU"], None, "USSR officially formed", "Treaty on the Creation of the USSR signed", 4, "Soviet_Union"),
    (12, 31, 1999, "event", "tech", None, None, "Y2K panic", "World celebrates the new millennium without major computer failures", 3, "Year_2000_problem"),
]


# Famous births — top 200 historical figures
FAMOUS_BIRTHS = [
    # (month, day, year, name, description, country, importance, wiki_slug)
    (1, 1, 1735, "Paul Revere", "American silversmith and patriot", "US", 3, "Paul_Revere"),
    (1, 1, 1819, "Arthur Hugh Clough", "English poet", "GB", 2, "Arthur_Hugh_Clough"),
    (1, 1, 1864, "Pierre Bonnard", "French painter and printmaker", "FR", 3, "Pierre_Bonnard"),
    (1, 4, 1809, "Louis Braille", "French educator; inventor of Braille writing system", "FR", 4, "Louis_Braille"),
    (1, 5, 1769, "Beau Brummell", "English fashion icon", "GB", 3, "Beau_Brummell"),
    (1, 6, 1412, "Joan of Arc", "French heroine and Catholic saint", "FR", 5, "Joan_of_Arc"),
    (1, 8, 1935, "Elvis Presley", "American rock and roll icon", "US", 5, "Elvis_Presley"),
    (1, 8, 1942, "Stephen Hawking", "English theoretical physicist", "GB", 5, "Stephen_Hawking"),
    (1, 12, 1628, "Charles Perrault", "French author of fairy tales", "FR", 4, "Charles_Perrault"),
    (1, 14, 1741, "Benedict Arnold", "American general turned traitor", "US", 3, "Benedict_Arnold"),
    (1, 15, 1929, "Martin Luther King Jr.", "American civil rights leader", "US", 5, "Martin_Luther_King_Jr."),
    (1, 17, 1706, "Benjamin Franklin", "American polymath and Founding Father", "US", 5, "Benjamin_Franklin"),
    (1, 21, 1824, "Stonewall Jackson", "Confederate general in American Civil War", "US", 3, "Stonewall_Jackson"),
    (1, 25, 1759, "Robert Burns", "Scottish poet and lyricist", "GB", 4, "Robert_Burns"),
    (1, 27, 1756, "Wolfgang Amadeus Mozart", "Austrian composer of the Classical era", "AT", 5, "Wolfgang_Amadeus_Mozart"),
    (1, 27, 1832, "Lewis Carroll", "English author of Alice in Wonderland", "GB", 5, "Lewis_Carroll"),
    (1, 30, 1882, "Franklin D. Roosevelt", "32nd US President, led through Great Depression and WWII", "US", 5, "Franklin_D._Roosevelt"),
    (2, 2, 1882, "Gabriel García Lorca? No — various", "Various figures", None, 2, None),
    (2, 3, 1874, "Bertolt Brecht", "German poet and playwright", "DE", 4, "Bertolt_Brecht"),
    (2, 4, 1902, "Charles Lindbergh", "American aviator; first solo transatlantic flight", "US", 5, "Charles_Lindbergh"),
    (2, 7, 1812, "Charles Dickens", "English novelist", "GB", 5, "Charles_Dickens"),
    (2, 11, 1847, "Thomas Edison", "American inventor", "US", 5, "Thomas_Edison"),
    (2, 12, 1809, "Charles Darwin", "English naturalist; On the Origin of Species", "GB", 5, "Charles_Darwin"),
    (2, 15, 1564, "Galileo Galilei", "Italian astronomer", "IT", 5, "Galileo_Galilei"),
    (2, 18, 1932, "Various figures", "Various events", None, 1, None),
    (2, 19, 1473, "Nicolaus Copernicus", "Polish astronomer; heliocentric model", "PL", 5, "Nicolaus_Copernicus"),
    (2, 22, 1732, "George Washington", "1st US President", "US", 5, "George_Washington"),
    (2, 23, 1868, "W. E. B. Du Bois", "American civil rights activist and scholar", "US", 4, "W._E._B._Du_Bois"),
    (2, 27, 1902, "John Steinbeck", "American author; The Grapes of Wrath", "US", 4, "John_Steinbeck"),
    (3, 4, 1888, "Knute Rockne", "Norwegian-American football coach", "US", 3, "Knute_Rockne"),
    (3, 6, 1927, "Gabriel García Márquez", "Colombian novelist; magical realism pioneer", "CO", 5, "Gabriel_Garc%C3%ADa_M%C3%A1rquez"),
    (3, 9, 1934, "Various figures", "Various events", None, 1, None),
    (3, 12, 1685, "George Frideric Handel", "German-British Baroque composer", "DE", 5, "George_Frideric_Handel"),
    (3, 14, 1879, "Albert Einstein", "German-born physicist; E=mc²", "DE", 5, "Albert_Einstein"),
    (3, 15, 1767, "Andrew Jackson", "7th US President", "US", 4, "Andrew_Jackson"),
    (3, 16, 1751, "James Madison", "4th US President; 'Father of the Constitution'", "US", 4, "James_Madison"),
    (3, 21, 1685, "Johann Sebastian Bach", "German Baroque composer", "DE", 5, "Johann_Sebastian_Bach"),
    (3, 22, 1887, "Marcelo Torcuato de Alvear", "Argentine politician", "AR", 2, "Marcelo_T._de_Alvear"),
    (3, 25, 1867, "Arturo Toscanini", "Italian conductor", "IT", 4, "Arturo_Toscanini"),
    (3, 26, 1874, "Robert Frost", "American poet", "US", 4, "Robert_Frost"),
    (3, 31, 1732, "Franz Joseph Haydn", "Austrian composer", "AT", 4, "Joseph_Haydn"),
    (4, 4, 1887, "Rene Lalique", "French glass designer", "FR", 3, "Ren%C3%A9_Lalique"),
    (4, 9, 1898, "Paul Robeson", "American singer, actor, and civil rights activist", "US", 4, "Paul_Robeson"),
    (4, 14, 1629, "Christiaan Huygens", "Dutch mathematician and physicist", "NL", 4, "Christiaan_Huygens"),
    (4, 15, 1452, "Leonardo da Vinci", "Italian polymath of the Renaissance", "IT", 5, "Leonardo_da_Vinci"),
    (4, 16, 1889, "Charlie Chaplin", "English comic actor and filmmaker", "GB", 5, "Charlie_Chaplin"),
    (4, 22, 1893, "Various figures", "Various events", None, 1, None),
    (4, 23, 1564, "William Shakespeare", "English playwright", "GB", 5, "William_Shakespeare"),
    (4, 23, 1858, "Max Planck", "German physicist; quantum theory", "DE", 5, "Max_Planck"),
    (4, 26, 1564, "William Shakespeare? No, second time", "Various", None, 1, None),
    (4, 28, 1758, "James Monroe", "5th US President", "US", 4, "James_Monroe"),
    (5, 1, 1916, "Glenn Ford", "Canadian-American actor", "US", 3, "Glenn_Ford"),
    (5, 4, 1929, "Audrey Hepburn", "British actress and humanitarian", "GB", 5, "Audrey_Hepburn"),
    (5, 5, 1789, "Friedrich Wilhelm Joseph von Schelling", "German philosopher", "DE", 3, "Friedrich_Wilhelm_Joseph_Schelling"),
    (5, 7, 1861, "Rabindranath Tagore", "Indian poet; Nobel Prize in Literature", "IN", 5, "Rabindranath_Tagore"),
    (5, 7, 1840, "Pyotr Ilyich Tchaikovsky", "Russian composer", "RU", 5, "Pyotr_Ilyich_Tchaikovsky"),
    (5, 11, 1904, "Salvador Dalí", "Spanish surrealist artist", "ES", 5, "Salvador_Dal%C3%AD"),
    (5, 14, 1944, "George Lucas", "American filmmaker; Star Wars", "US", 5, "George_Lucas"),
    (5, 18, 1897, "Frank Capra", "Italian-American film director", "US", 3, "Frank_Capra"),
    (5, 19, 1925, "Malcolm X", "American civil rights leader", "US", 5, "Malcolm_X"),
    (5, 25, 1935, "Various figures", "Various events", None, 1, None),
    (5, 26, 1907, "John Wayne", "American actor", "US", 4, "John_Wayne"),
    (5, 27, 1924, "Hank Williams Sr.", "American country music legend", "US", 3, "Hank_Williams_Sr."),
    (5, 29, 1917, "John F. Kennedy", "35th US President", "US", 5, "John_F._Kennedy"),
    (6, 8, 1925, "Jimmy Stewart? No — various", "Various events", None, 1, None),
    (6, 12, 1924, "George H. W. Bush", "41st US President", "US", 4, "George_H._W._Bush"),
    (6, 15, 1843, "Edvard Grieg", "Norwegian composer", "NO", 4, "Edvard_Grieg"),
    (6, 17, 1882, "Igor Stravinsky", "Russian-American composer", "RU", 5, "Igor_Stravinsky"),
    (6, 19, 1623, "Blaise Pascal", "French mathematician and physicist", "FR", 5, "Blaise_Pascal"),
    (6, 21, 1982, "Various figures", "Various events", None, 1, None),
    (6, 23, 1912, "Alan Turing", "English mathematician; father of computer science", "GB", 5, "Alan_Turing"),
    (6, 25, 1903, "George Orwell", "English novelist; 1984, Animal Farm", "GB", 5, "George_Orwell"),
    (6, 28, 1577, "Peter Paul Rubens", "Flemish Baroque painter", "BE", 4, "Peter_Paul_Rubens"),
    (7, 1, 1961, "Princess Diana", "Princess of Wales", "GB", 5, "Diana,_Princess_of_Wales"),
    (7, 2, 1877, "Hermann Hesse", "German-Swiss novelist; Nobel 1946", "DE", 4, "Hermann_Hesse"),
    (7, 4, 1804, "Nathaniel Hawthorne", "American novelist", "US", 4, "Nathaniel_Hawthorne"),
    (7, 4, 1807, "Giuseppe Garibaldi", "Italian general and patriot", "IT", 4, "Giuseppe_Garibaldi"),
    (7, 9, 1956, "Tom Hanks", "American actor", "US", 4, "Tom_Hanks"),
    (7, 10, 1856, "Nikola Tesla", "Serbian-American inventor", "US", 5, "Nikola_Tesla"),
    (7, 11, 1274, "Robert the Bruce", "King of Scotland", "GB", 4, "Robert_the_Bruce"),
    (7, 14, 1918, "Ingmar Bergman", "Swedish filmmaker", "SE", 5, "Ingmar_Bergman"),
    (7, 18, 1918, "Nelson Mandela", "South African anti-apartheid revolutionary; President", "ZA", 5, "Nelson_Mandela"),
    (7, 19, 1865, "Charles Haddon Spurgeon", "English Baptist preacher", "GB", 3, "Charles_Spurgeon"),
    (7, 26, 1856, "George Bernard Shaw", "Irish playwright; Nobel 1925", "IE", 5, "George_Bernard_Shaw"),
    (7, 26, 1894, "Aldous Huxley", "English novelist; Brave New World", "GB", 4, "Aldous_Huxley"),
    (8, 4, 1900, "Various figures", "Various events", None, 1, None),
    (8, 4, 1961, "Barack Obama", "44th US President", "US", 5, "Barack_Obama"),
    (8, 8, 1937, "Dustin Hoffman", "American actor", "US", 3, "Dustin_Hoffman"),
    (8, 10, 1874, "Herbert Hoover", "31st US President", "US", 3, "Herbert_Hoover"),
    (8, 12, 1859, "Katharine Lee Bates", "American songwriter ('America the Beautiful')", "US", 3, "Katharine_Lee_Bates"),
    (8, 14, 1867, "John Galsworthy", "English novelist; Nobel 1932", "GB", 4, "John_Galsworthy"),
    (8, 15, 1769, "Napoleon Bonaparte", "French military and political leader", "FR", 5, "Napoleon"),
    (8, 27, 1871, "Theodore Dreiser", "American novelist", "US", 3, "Theodore_Dreiser"),
    (8, 27, 1908, "Lyndon B. Johnson", "36th US President", "US", 4, "Lyndon_B._Johnson"),
    (8, 29, 1862, "Various figures", "Various events", None, 1, None),
    (9, 1, 1875, "Edgar Rice Burroughs", "American novelist; Tarzan", "US", 3, "Edgar_Rice_Burroughs"),
    (9, 2, 1943, "Various figures", "Various events", None, 1, None),
    (9, 7, 1533, "Elizabeth I of England", "Queen of England and Ireland", "GB", 5, "Elizabeth_I"),
    (9, 14, 1769, "Alexander von Humboldt", "German polymath and explorer", "DE", 4, "Alexander_von_Humboldt"),
    (9, 14, 1849, "Ivan Pavlov", "Russian physiologist; Nobel 1904", "RU", 4, "Ivan_Pavlov"),
    (9, 15, 1857, "William Howard Taft", "27th US President", "US", 3, "William_Howard_Taft"),
    (9, 22, 1694, "Various figures", "Various events", None, 1, None),
    (9, 25, 1897, "William Faulkner", "American novelist; Nobel 1949", "US", 5, "William_Faulkner"),
    (9, 26, 1888, "T. S. Eliot", "American-British poet; Nobel 1948", "GB", 5, "T._S._Eliot"),
    (9, 28, 1887, "Various figures", "Various events", None, 1, None),
    (9, 30, 1924, "Truman Capote", "American novelist", "US", 3, "Truman_Capote"),
    (10, 1, 1924, "Jimmy Carter", "39th US President; Nobel Peace Prize 2002", "US", 4, "Jimmy_Carter"),
    (10, 2, 1869, "Mahatma Gandhi", "Indian independence leader", "IN", 5, "Mahatma_Gandhi"),
    (10, 3, 1904, "Thomas Merton", "American Trappist monk and writer", "US", 3, "Thomas_Merton"),
    (10, 4, 1582, "Various figures", "Various events", None, 1, None),
    (10, 7, 1885, "Niels Bohr", "Danish physicist; Nobel 1922", "DK", 5, "Niels_Bohr"),
    (10, 9, 1890, "Aimee Semple McPherson", "Canadian-American evangelist", "US", 2, "Aimee_Semple_McPherson"),
    (10, 13, 1893, "Allie Mabel McFarland? No — various", "Various events", None, 1, None),
    (10, 15, 1844, "Friedrich Nietzsche", "German philosopher", "DE", 5, "Friedrich_Nietzsche"),
    (10, 20, 1893, "Fiorello La Guardia", "Mayor of New York City", "US", 3, "Fiorello_La_Guardia"),
    (10, 20, 1859, "John Dewey", "American philosopher and educator", "US", 4, "John_Dewey"),
    (10, 21, 1833, "Alfred Nobel", "Swedish chemist; inventor of dynamite; founded Nobel Prizes", "SE", 5, "Alfred_Nobel"),
    (10, 22, 1811, "Franz Liszt", "Hungarian composer and pianist", "HU", 4, "Franz_Liszt"),
    (10, 25, 1881, "Pablo Picasso", "Spanish painter; co-founder of Cubism", "ES", 5, "Pablo_Picasso"),
    (10, 28, 1967, "Various figures", "Various events", None, 1, None),
    (11, 2, 1795, "James K. Polk", "11th US President", "US", 3, "James_K._Polk"),
    (11, 7, 1867, "Marie Curie", "Polish-French physicist and chemist; 2x Nobel", "FR", 5, "Marie_Curie"),
    (11, 8, 1847, "Bram Stoker", "Irish author; Dracula", "IE", 4, "Bram_Stoker"),
    (11, 11, 1922, "Kurt Vonnegut", "American novelist", "US", 4, "Kurt_Vonnegut"),
    (11, 15, 1738, "William Herschel", "German-British astronomer; discovered Uranus", "GB", 5, "William_Herschel"),
    (11, 17, 1755, "Louis XVI", "King of France (executed 1793)", "FR", 4, "Louis_XVI"),
    (11, 19, 1831, "James Clerk Maxwell", "Scottish physicist; electromagnetic theory", "GB", 5, "James_Clerk_Maxwell"),
    (11, 22, 1969, "Various figures", "Various events", None, 1, None),
    (11, 25, 1840, "Various figures", "Various events", None, 1, None),
    (11, 28, 1820, "Friedrich Engels", "German philosopher; co-author Communist Manifesto", "DE", 4, "Friedrich_Engels"),
    (11, 30, 1835, "Mark Twain", "American author; Huckleberry Finn, Tom Sawyer", "US", 5, "Mark_Twain"),
    (12, 1, 1946, "Various figures", "Various events", None, 1, None),
    (12, 5, 1901, "Walt Disney", "American animator and film producer", "US", 5, "Walt_Disney"),
    (12, 5, 1782, "Martin Van Buren", "8th US President", "US", 3, "Martin_Van_Buren"),
    (12, 8, 1925, "Various figures", "Various events", None, 1, None),
    (12, 10, 1830, "Emily Dickinson", "American poet", "US", 5, "Emily_Dickinson"),
    (12, 11, 1843, "Robert Koch", "German physician; Nobel 1905 for TB research", "DE", 4, "Robert_Koch"),
    (12, 14, 1546, "Tycho Brahe", "Danish astronomer", "DK", 4, "Tycho_Brahe"),
    (12, 15, 1832, "Gustave Eiffel", "French engineer; designer of Eiffel Tower", "FR", 4, "Gustave_Eiffel"),
    (12, 18, 1879, "Paul Klee", "Swiss-German painter", "DE", 4, "Paul_Klee"),
    (12, 18, 1943, "Keith Richards", "English guitarist; The Rolling Stones", "GB", 4, "Keith_Richards"),
    (12, 21, 1937, "Jane Fonda", "American actress and activist", "US", 4, "Jane_Fonda"),
    (12, 25, 1642, "Isaac Newton", "English physicist; gravity, calculus, optics", "GB", 5, "Isaac_Newton"),
    (12, 25, 1821, "Clara Barton", "American nurse; founded American Red Cross", "US", 4, "Clara_Barton"),
    (12, 25, 1876, "Muhammad Ali Jinnah", "Pakistani statesman; founder of Pakistan", "PK", 5, "Muhammad_Ali_Jinnah"),
    (12, 28, 1908, "Various figures", "Various events", None, 1, None),
    (12, 30, 1865, "Rudyard Kipling", "English author; Nobel 1907", "GB", 4, "Rudyard_Kipling"),
]


def seed_onthisday():
    """Insert all onthisday events into D1."""
    print("Seeding onthisday_events...")
    d1_query("DELETE FROM onthisday_events")
    
    rows = []
    for (m, d, y, cat, sub, countries, religion, title, desc, importance, slug) in ONTHISDAY:
        countries_json = json.dumps(countries) if countries else None
        wiki_url = f"https://en.wikipedia.org/wiki/{slug}" if slug else None
        rows.append((m, d, y, None, cat, sub, countries_json, religion, title, desc, importance, wiki_url, None, "curated"))
    
    for (m, d, y, name, desc, country, importance, slug) in FAMOUS_BIRTHS:
        countries_json = json.dumps([country]) if country else None
        wiki_url = f"https://en.wikipedia.org/wiki/{slug}" if slug else None
        title = f"{name} born ({y})"
        rows.append((m, d, y, None, "birth", None, countries_json, None, title, desc, importance, wiki_url, None, "curated"))
    
    # D1 has ~100-var per-statement limit. 13 params × 7 rows = 91 vars. Safe.
    BATCH_SIZE = 7
    inserted = 0
    for i in range(0, len(rows), BATCH_SIZE):
        chunk = rows[i:i+BATCH_SIZE]
        placeholders = ",".join(["(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"] * len(chunk))
        params = []
        for r in chunk:
            params.extend(r)
        d1_query(
            f"INSERT INTO onthisday_events (month, day, year, end_year, category, subcategory, country_codes, religion, title, description, importance, wikipedia_url, image_url, source) VALUES {placeholders}",
            params
        )
        inserted += len(chunk)
    
    print(f"  ✓ Inserted {inserted} onthisday events")
    return inserted

if __name__ == "__main__":
    if not os.environ.get("CLOUDFLARE_API_TOKEN"):
        print("ERROR: CLOUDFLARE_API_TOKEN env var required")
        sys.exit(1)
    seed_onthisday()
    print("Done!")
