-- ============================================================
-- Phase 8: missing countries + timezones for cities15000 import
-- Locked 2026-07-19
-- Reference: docs/architecture/SHARED-DB-PLAN.md
-- ============================================================
--
-- cities15000.zip references 244 countries and 356 timezones.
-- The original 5,081-city DB had 194 countries and 312 timezones.
-- We need the missing 50 countries and 96 timezones to import
-- cities15000 without FK constraint failures.
--
-- For territories, we use Wikipedia / GeoNames references.
-- For timezones, we use Python zoneinfo to get current offset
-- and abbreviation.

-- ---------- 1. Missing countries (territories, mostly) ----------
-- Generated by comparing cities15000.txt to existing countries.
-- Using `INSERT OR IGNORE` so re-runs are safe.
INSERT OR IGNORE INTO countries (cca2, cca3, ccn3, name, ascii_name, continent, capital, area_km2)
VALUES
  ('AS', 'ASM', '016', 'American Samoa', 'American Samoa', 'OC', 'Pago Pago', 199),
  ('AW', 'ABW', '533', 'Aruba', 'Aruba', NULL, 'Oranjestad', 180),
  ('AI', 'AIA', '660', 'Anguilla', 'Anguilla', NULL, 'The Valley', 91),
  ('AQ', 'ATA', '010', 'Antarctica', 'Antarctica', 'AN', NULL, 14000000),
  ('BL', 'BLM', '652', 'Saint Barthélemy', 'Saint Barthelemy', NULL, 'Gustavia', 21),
  ('BM', 'BMU', '060', 'Bermuda', 'Bermuda', NULL, 'Hamilton', 54),
  ('BQ', 'BES', '535', 'Caribbean Netherlands', 'Caribbean Netherlands', NULL, 'Kralendijk', 328),
  ('BV', 'BVT', '074', 'Bouvet Island', 'Bouvet Island', 'AN', NULL, 49),
  ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', NULL, 'West Island', 14),
  ('CK', 'COK', '184', 'Cook Islands', 'Cook Islands', 'OC', 'Avarua', 236),
  ('CW', 'CUW', '531', 'Curaçao', 'Curacao', NULL, 'Willemstad', 444),
  ('CX', 'CXR', '162', 'Christmas Island', 'Christmas Island', 'OC', 'Flying Fish Cove', 135),
  ('EH', 'ESH', '732', 'Western Sahara', 'Western Sahara', 'AF', 'El Aaiún', 266000),
  ('FK', 'FLK', '238', 'Falkland Islands', 'Falkland Islands', NULL, 'Stanley', 12173),
  ('FO', 'FRO', '234', 'Faroe Islands', 'Faroe Islands', 'EU', 'Tórshavn', 1393),
  ('GF', 'GUF', '254', 'French Guiana', 'French Guiana', 'SA', 'Cayenne', 83534),
  ('GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', 'EU', 'Gibraltar', 6),
  ('GL', 'GRL', '304', 'Greenland', 'Greenland', 'NA', 'Nuuk', 2166086),
  ('GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', NULL, 'Basse-Terre', 1628),
  ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong', 'AS', 'Hong Kong', 1104),
  ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'AN', NULL, 412),
  ('IO', 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory', NULL, 'Diego Garcia', 60),
  ('JE', 'JEY', '832', 'Jersey', 'Jersey', 'EU', 'Saint Helier', 116),
  ('KY', 'CYM', '136', 'Cayman Islands', 'Cayman Islands', NULL, 'George Town', 264),
  ('LI', 'LIE', '438', 'Liechtenstein', 'Liechtenstein', 'EU', 'Vaduz', 160),
  ('MC', 'MCO', '492', 'Monaco', 'Monaco', 'EU', 'Monaco', 2),
  ('MF', 'MAF', '663', 'Saint Martin', 'Saint Martin', NULL, 'Marigot', 53),
  ('MO', 'MAC', '446', 'Macao', 'Macao', 'AS', 'Macao', 30),
  ('MP', 'MNP', '580', 'Northern Mariana Islands', 'Northern Mariana Islands', 'OC', 'Saipan', 464),
  ('MQ', 'MTQ', '474', 'Martinique', 'Martinique', NULL, 'Fort-de-France', 1128),
  ('MS', 'MSR', '500', 'Montserrat', 'Montserrat', NULL, 'Plymouth', 102),
  ('NC', 'NCL', '540', 'New Caledonia', 'New Caledonia', 'OC', 'Nouméa', 18575),
  ('NU', 'NIU', '570', 'Niue', 'Niue', 'OC', 'Alofi', 260),
  ('PF', 'PYF', '258', 'French Polynesia', 'French Polynesia', 'OC', 'Papeete', 4167),
  ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', NULL, 'Saint-Pierre', 242),
  ('PN', 'PCN', '612', 'Pitcairn', 'Pitcairn', 'OC', 'Adamstown', 47),
  ('PR', 'PRI', '630', 'Puerto Rico', 'Puerto Rico', NULL, 'San Juan', 9104),
  ('PS', 'PSE', '275', 'Palestine', 'Palestine', 'AS', 'Ramallah', 6020),
  ('RE', 'REU', '638', 'Réunion', 'Reunion', 'AF', 'Saint-Denis', 2511),
  ('SH', 'SHN', '654', 'Saint Helena', 'Saint Helena', 'AF', 'Jamestown', 394),
  ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'EU', 'Longyearbyen', 62045),
  ('SM', 'SMR', '674', 'San Marino', 'San Marino', 'EU', 'San Marino', 61),
  ('SX', 'SXM', '534', 'Sint Maarten', 'Sint Maarten', NULL, 'Philipsburg', 34),
  ('TC', 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', NULL, 'Cockburn Town', 948),
  ('TF', 'ATF', '260', 'French Southern Territories', 'French Southern Territories', 'AN', 'Port-aux-Français', 7747),
  ('TK', 'TKL', '772', 'Tokelau', 'Tokelau', 'OC', 'None', 12),
  ('TL', 'TLS', '626', 'Timor-Leste', 'Timor-Leste', 'OC', 'Dili', 14874),
  ('UM', 'UMI', '581', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'OC', NULL, 34),
  ('VA', 'VAT', '336', 'Vatican City', 'Vatican City', 'EU', 'Vatican City', 0),
  ('VG', 'VGB', '092', 'British Virgin Islands', 'British Virgin Islands', NULL, 'Road Town', 151),
  ('VI', 'VIR', '850', 'U.S. Virgin Islands', 'U.S. Virgin Islands', NULL, 'Charlotte Amalie', 347),
  ('WF', 'WLF', '876', 'Wallis and Futuna', 'Wallis and Futuna', 'OC', 'Mata-Utu', 142),
  ('YT', 'MYT', '175', 'Mayotte', 'Mayotte', 'AF', 'Mamoudzou', 374);

-- ---------- 2. Missing timezones ----------
-- Insert missing timezones with best-effort metadata.
-- Source: Python zoneinfo (IANA tzdata) for offset/abbreviation.
-- We populate region, subregion, city, country_codes, latitude,
-- longitude, current_offset, current_abbreviation, is_dst.

-- We'll insert these via a Python seed script (seed/missing_tzs.py)
-- because the data is too long to embed here. See that file.
