/**
 * Day Report generator (data layer)
 *
 * Per Blueprint Ch 8 (Feature #1: Birthday AI Report):
 *   - 400-800 word cited narrative for any date
 *   - Printable PDF (via pdfkit)
 *   - Square social share card
 *   - Free teaser: 3 cited facts + blurred poster preview
 *
 * This is the data layer (no checkout flow, no auth UI).
 * $4.99 product per MyHeritage pattern (82M uses).
 *
 * Source: Blueprint Ch 8 (Feature #1) + Risk #3 (free chatbot cannibalization)
 */

const fs = require('fs');
const path = require('path');

/**
 * Compute the top 3 facts for a date (free teaser).
 * @param {object[]} entries
 * @param {number} month
 * @param {number} day
 * @returns {object[]}
 */
function computeTeaser(entries, month, day) {
  const dayEntries = entries.filter(e => e.month === month && e.day === day);

  return dayEntries
    .sort((a, b) => (b.rank_score || 0) - (a.rank_score || 0))
    .slice(0, 3)
    .map(e => ({
      title: e.title,
      year: e.year,
      type: e.type,
      description: e.description,
      image_url: e.image_url,
      wikipedia_url: e.wikipedia_url,
      source_record_id: e.wikidata_id || e.wikipedia_title,
      rank_score: e.rank_score || 0
    }));
}

/**
 * Build a full Day Report structure (citable 400-800 word narrative scaffold).
 * The actual narrative text would be generated by an LLM (Gemini Flash-Lite)
 * in a separate step using this scaffold.
 *
 * @param {object[]} entries
 * @param {number} month
 * @param {number} day
 * @param {number} year - focus year (e.g. 1985 for "the world in 1985")
 * @param {object} [opts] - {includeBirths, includeDeaths, includeEvents, maxItems}
 * @returns {object} report structure
 */
function buildReport(entries, month, day, year, opts = {}) {
  const includeBirths = opts.includeBirths ?? true;
  const includeDeaths = opts.includeDeaths ?? true;
  const includeEvents = opts.includeEvents ?? true;
  const maxItems = opts.maxItems ?? 20;

  const dateKey = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  const dateName = formatDateName(month, day);

  // Filter by year if specified
  let yearEntries = year ? entries.filter(e => e.year === year) : entries;
  yearEntries = yearEntries.filter(e => e.month === month && e.day === day);

  // Split by type
  const events = includeEvents
    ? yearEntries.filter(e => e.type === 'event').sort((a, b) => (b.rank_score || 0) - (a.rank_score || 0))
    : [];
  const births = includeBirths
    ? yearEntries.filter(e => e.type === 'birth').sort((a, b) => (b.rank_score || 0) - (a.rank_score || 0))
    : [];
  const deaths = includeDeaths
    ? yearEntries.filter(e => e.type === 'death').sort((a, b) => (b.rank_score || 0) - (a.rank_score || 0))
    : [];

  // Build narrative scaffold (template-driven, no LLM)
  const scaffold = {
    title: `The World on ${dateName}, ${year || 'History'}`,
    subtitle: year
      ? `A snapshot of events, births, and deaths from ${year}`
      : `A look at what happened throughout history on ${dateName}`,
    sections: []
  };

  if (events.length > 0) {
    scaffold.sections.push({
      heading: `Major Events (${year || 'in History'})`,
      intro: year
        ? `Here are the notable events that took place on ${dateName}, ${year}:`
        : `Here are the notable events that took place on ${dateName} throughout history:`,
      items: events.slice(0, maxItems).map(e => ({
        title: e.title,
        description: e.description,
        year: e.year,
        wikipedia_url: e.wikipedia_url,
        wikidata_id: e.wikidata_id,
        image_url: e.image_url,
        citation: `[Record #${e.wikidata_id || e.id || 'unknown'}]`
      }))
    });
  }

  if (births.length > 0) {
    scaffold.sections.push({
      heading: `Famous People Born on ${dateName}`,
      intro: `People who share this birthday:`,
      items: births.slice(0, maxItems).map(b => ({
        title: b.title,
        description: b.description,
        year: b.year,
        wikipedia_url: b.wikipedia_url,
        wikidata_id: b.wikidata_id,
        image_url: b.image_url,
        birth_year: b.year,
        star_sign: b.star_sign,
        chinese_zodiac: b.chinese_zodiac,
        generation: b.generation,
        citation: `[Record #${b.wikidata_id || b.id || 'unknown'}]`
      }))
    });
  }

  if (deaths.length > 0) {
    scaffold.sections.push({
      heading: `Notable Deaths on ${dateName}`,
      intro: `Remembering those who left us on this day:`,
      items: deaths.slice(0, maxItems).map(d => ({
        title: d.title,
        description: d.description,
        year: d.year,
        wikipedia_url: d.wikipedia_url,
        wikidata_id: d.wikidata_id,
        image_url: d.image_url,
        citation: `[Record #${d.wikidata_id || d.id || 'unknown'}]`
      }))
    });
  }

  // Word count estimate (intro + items)
  const wordCount = scaffold.sections.reduce((sum, section) => {
    const introWords = (section.intro || '').split(/\s+/).length;
    const itemWords = section.items.reduce((s, item) => s + (item.description || '').split(/\s+/).length, 0);
    return sum + introWords + itemWords;
  }, 0);

  return {
    ...scaffold,
    date: dateKey,
    dateName,
    year,
    wordCount,
    targetWordCount: { min: 400, max: 800 },
    needsLLM: wordCount < 400,  // flag if LLM needs to expand
    sources: collectSources(yearEntries),
    generated_at: new Date().toISOString()
  };
}

/**
 * Collect all data sources cited in the report.
 */
function collectSources(entries) {
  const sources = new Set();
  for (const e of entries) {
    if (e.data_sources) {
      try {
        JSON.parse(e.data_sources).forEach(s => sources.add(s.name));
      } catch (err) { /* skip */ }
    }
  }
  return [...sources];
}

/**
 * Save a report structure as JSON.
 */
function saveReport(report, outputDir = '/tmp/otd-reports') {
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
  const filename = `${report.date}.json`;
  fs.writeFileSync(path.join(outputDir, filename), JSON.stringify(report, null, 2));
  return filename;
}

function formatDateName(month, day) {
  const months = ['', 'January', 'February', 'March', 'April', 'May', 'June',
                  'July', 'August', 'September', 'October', 'November', 'December'];
  return `${months[month]} ${day}`;
}

module.exports = {
  computeTeaser,
  buildReport,
  saveReport,
  formatDateName
};
